### ISSUE TITLE
Apply GHA Templates to Select Repositories 

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/opensearch-build#117]
Apply the GHA Templates in #116 to the following repositories as a reference implementation for the other repository owners.

- [ ] [common-utils](https://github.com/opensearch-project/common-utils)
- [ ] [job-scheduler](https://github.com/opensearch-project/job-scheduler)
- [ ] [anomaly-detection](https://github.com/opensearch-project/anomaly-detection)
