### ISSUE TITLE
[META] Test orchestration framework

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#122]
This is a meta issue for defining the test orchestration framework as part of automated test infra

### Summary of Action plan
todo

### Roles and Responsibilities 
1. Orchestration framework will provide s3 location to publish logs as part of configuration parameters for a job. It is the responsibility of each job to publish its own logs to that s3 location.

### Tasks 
Please note these P0s are defined according to prod readiness for 1.1 release

#### P0

- [x] Define syntax of manifest file and S3 location. See https://github.com/opensearch-project/opensearch-build/issues/111
- [x] #173
- [x] Create _artifact reader_ stage, that reads artifacts from s3, reads manifest file for each artifact and extracts parameters to run testing jobs.
- [x] Create _test executor_ stage, that uses those parameters to kick off multiple parallel testing jobs on provided artifact.
- [x] #176
- [x] #175
- [x] #174
- [x] #317
- [x] #283 
- [x] #384
- [x] #262
- [x] #263 
- [x] #276 
- [x] #260 
- [x] Support notification/hooks to different systems #107 
- [x] #207 

P0 - non surge
- [x] #221

#### P1
- [x] #257
- [x] #1184
- [x] #211
