### ISSUE TITLE
[META] Performance benchmarking and testing

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#126]
This is a meta issue for defining the performance testing framework as part of automated test infra

Related tasks:
**P0**
- [ ] Create single node cluster for performance testing
- [ ] Integrate rally(networking, client etc.) with the single node cluster
- [ ] Integrate performance testing with jenkins for automation
- [ ] Publish human-readable test run reports as a simple HTML document

**P1**
- [ ] FUTURE IMPROVEMENTS - Instead of single node cluster, run performance tests on external multi-node clusters.

**Comment by Bukhtawar** [comment]
@dblock are we also looking to gate PR merges if they cause regression. This is important since we want to discover this earlier. We do not want to wait for a release only to discover a regression at which point it would get harder to pin point the exact commit(s)
