### ISSUE TITLE
[Meta] Build Surge end-to-end description

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#132]
This is a meta issue to track subtasks related to this surge.

This is the desired outcome:

High level flow
![image](https://user-images.githubusercontent.com/1594901/128047017-10ed3f7f-44a9-4b37-958d-80380d114470.png)

1. A central build job in this repo kicks off.  It reads a manifest file, clones core and each required plugin repository, builds it and pushes a bleeding edge bundle, zips, and all maven publications to a new /builds folder under artifacts.opensearch.org and tags it as latest.
2. The test workflow will execute sometime after this job that picks up the latest build and executes all required tests.  On success the artifact is promoted directly to /release-candidates. (Follow up is to link these two workflows together with sns).
3. A release workflow is executed on release day that signs and promotes artifacts to /releases and maven central as necessary.

Manifest format
https://github.com/opensearch-project/opensearch-build/issues/111

- [x] [Script to build each component and assemble bundle](https://github.com/opensearch-project/opensearch-build/issues/133)
- [x] [Manifest File Creation](https://github.com/opensearch-project/opensearch-build/issues/134)
- [x] [Create GHA that executes scripts and uploads output to S3](https://github.com/opensearch-project/opensearch-build/issues/135)
- [ ] [Promotion workflow](#136 )

**Comment by adnapibar** [comment]
These are the list of artifacts from the `OpenSearch` repository that I think we need to publish to Maven Central. 

```
Server (org.opensearch)
    opensearch
Client (org.opensearch.client)
    opensearch-rest-high-level-client
    transport
    opensearch-rest-client
    opensearch-rest-client-sniffer
Libs (org.opensearch)
    opensearch-cli
    opensearch-core
    opensearch-dissect
    opensearch-geo
    opensearch-grok
    opensearch-nio
    opensearch-plugin-classloader
    opensearch-secure-sm
    opensearch-ssl-config
    opensearch-x-content
Plugins (org.opensearch.plugin)
    aggs-matrix-stats-client
    analysis-icu-client
    lang-mustache-client
    mapper-extras-client
    parent-join-client
    percolator-client
    rank-eval-client
    reindex-client
    transport-netty4-client
    transport-nio-client
Test (org.opensearch.test)
    framework
```

**Comment by mch2** [comment]
Closing this as outdated - https://github.com/opensearch-project/opensearch-build/projects/4 holds remaining work for bundle-workflow.
