### ISSUE TITLE
[Meta] Automate the OpenSearch release process

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#1361]
OpenSearch / OpenSearch Dashboards have a number of elements to the release process that should be automated to make sure there is consistent and timely delivery of artifacts.

### Preparation
- [x] Create default build manifest
  * #461
- [x] Create release tracking ticket
  * #531
- [x] #1366
- [x] Track component onboarding state
- [x] https://github.com/opensearch-project/opensearch-build/issues/1899
- [x] Notification when preparation is complete and we have a 'full build'
- [x] Generate testing guide that can be used to pickup the latest version
- [x] File issues for components, or other release processes like retrospective

### Development
- [x] Run tests suites, integration / bwc / perf tests
  * #604
  * #818
  * #90
  * #693
- [x] For test suites results, create issues on components failures
- [x] Track component issue counts state
- [ ] When critical dates arrive, make notifications about things that are need to be resolved
- [ ] Create a way to pick 'release candidate' that is available for testing, generate all the test documentation for how to pick it up
- [x] https://github.com/opensearch-project/opensearch-build/issues/1689
- [ ] If issues get opened up after there is an active release candidate link it to the release issue so it can be triaged by the distribution
- [ ] Track that all components have completed dev work to notify that release can start
- [x] https://github.com/opensearch-project/opensearch-build/issues/716
- [x] Release notes tracker to track if release notes exists or not based on latest commits
https://github.com/opensearch-project/opensearch-build/issues/2345
- [ ] https://github.com/opensearch-project/opensearch-build/issues/2545
- [x] https://github.com/opensearch-project/opensearch-build/issues/2546

### Releasing
- [x] From release candidate build, sign all artifacts
- [x] Publish signed artifacts to maven
  * #118
- [x] Promote signed artifacts to production s3 buckets 
    * #1351
    * #1332
    * #1355
- [x] Run validation on s3 bucket contents
  * #1358
- [ ] Create updated website sections for artifacts
- [x] Promote docker images
    * #859 
    * #928 
    * #929
    * #1318
- [x] Run validation on prod docker images
  * #1359
- [ ] Deploy updated website
- [ ] Send notifications about update build

### Cleanup
- [x] https://github.com/opensearch-project/opensearch-build/issues/378
- [x] https://github.com/opensearch-project/opensearch-build/issues/1898
- [ ] Track that all components cut a release (github release?)
- [x] Update manifest refs from branch to tags
- [ ] Slow down the branch build rate in check for build

**Comment by prudhvigodithi** [comment]
There are two META issues targeting the [Automation of entire OpenSearch Release ](https://github.com/opensearch-project/opensearch-build/issues/3676) and a [META issue](https://github.com/opensearch-project/opensearch-build/issues/4216) as perquisite for suggested improvements/enhancements to acheive the OpenSearch Release automation. Can we close this and track on the above two META issues? @dblock @bbarani @peternied please suggest.

**Comment by peternied** [comment]
@prudhvigodithi If you don't think this issue is useful feel free to close it.  Beforehand, I think it might be good to take an inventory of incomplete items from this issue.

**Comment by gaiksaya** [comment]
Marked the issues as resolved for most of tasks. Closing this one.
