### ISSUE TITLE
[META] Add tests for existing jenkins jobs

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1468]
### Is your feature request related to a problem? Please describe

Following up on the comment - https://github.com/opensearch-project/opensearch-build/issues/1444#issuecomment-1010324850

- [ ] Create a separate folder for tests for jenkins job
- [ ] #1712

The existing jenkins jobs needs tests - 

- [ ] [docker-build](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/docker/Jenkinsfile) job
- [ ] [opnesearch-dashboards-distribution-build](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch-dashboards/distribution-build.jenkinsfile) job
- [ ] [opensearch-ruby](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch-ruby/Jenkinsfile) job
- [ ] [opensearch-distribution-build](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile) job
- [ ] [tar-promotion](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/promotion/tar-promotion.jenkinsfile) job
- [ ] [whitesource-scan](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/vulnerability-scan/whitesource-scan.jenkinsfile) job
- [ ] [test-orchestrator](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/test/orchestrator/Jenkinsfile) job
- [ ] [testsuite](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/test/testsuite/Jenkinsfile) job
- [ ] [check-for-build](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/check-for-build.jenkinsfile) job
- [ ] Add a CI check to ensure all jenkins job have a test associated with it.

### Describe the solution you'd like

Every job should have a test associated with it, with a regression `txt` file inside `jenkinsjob-regression-files`

### Acceptance Criteria
- All the libraries should have a lib tester associated with it
- All the jenkins job should have a test associated with it that uses only lib testers for libraries
- A check is added in CI making sure every job has a test

**Comment by dblock** [comment]
> Let's create an issue for every task here when the work is begun. Thank you!

FWIW we have a lot of 1-line issues, I think it's totally fine to track a list like here, link to PRs as we go, then close the issue when we have 100% done

**Comment by prudhvigodithi** [comment]
The tests already exists for all shared libraries used by Jenkinsfiles, the functions are being fully tested.
Closing this issue, please feel free to reopen.
https://github.com/opensearch-project/opensearch-build/tree/main/tests/jenkins

**Comment by gaiksaya** [comment]
These tests for jenkinsFiles and not the libraries. We need to add tests for the existing jenkinsFile in this repo. Might need to revisit the list mentioned in description.

**Comment by jordarlu** [comment]
Hi, by reviewing the .jenkinsfile at repo, a few of them were either removed or moved to other location/folder. Here is the updated list for this issue to continue check..

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/chunglu/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/chunglu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



.jenkinsfile | location
-- | --
bwc-test.jenkinsfile | opensearch-build/jenkins/opensearch-dashboards/
distribution-build.jenkinsfile | opensearch-build/jenkins/opensearch-dashboards/
integ-test.jenkinsfile | opensearch-build/jenkins/opensearch-dashboards/
bwc-test.jenkinsfile | opensearch-build/jenkins/opensearch/
distribution-build.jenkinsfile | opensearch-build/jenkins/opensearch/
integ-test.jenkinsfile | opensearch-build/jenkins/opensearch/
perf-test.jenkinsfile | opensearch-build/jenkins/opensearch/
maven-sign-release.jenkinsfile | opensearch-build/jenkins/opensearch-maven-release/
opensearch-ruby.jenkinsfile | opensearch-build/jenkins/opensearch-ruby/
promote-artifacts.jenkinsfile | opensearch-build/jenkins/promotion/
promote-docker-ecr.jenkinsfile | opensearch-build/jenkins/promotion/
promote-yum-repos.jenkinsfile | opensearch-build/jenkins/promotion/
release-notes-check.jenkinsfile | opensearch-build/jenkins/release-notes-check/
release-tag.jenkinsfile | opensearch-build/jenkins/release-tag/
rpm-validation.jenkinsfile | opensearch-build/jenkins/rpm-validation/
sign-standalone-artifacts.jenkinsfile | opensearch-build/jenkins/sign-artifacts/
whitesource-scan.jenkinsfile | opensearch-build/jenkins/vulnerability-scan/
perf-test.jenkinsfile | opensearch-build/jenkins/cross-cluster-replication/
release-data-prepper-all-artifacts.jenkinsfile | opensearch-build/jenkins/data-prepper/
docker-build.jenkinsfile | opensearch-build/jenkins/docker/
docker-copy.jenkinsfile | opensearch-build/jenkins/docker/
docker-scan.jenkinsfile | opensearch-build/jenkins/docker/
gradle-check.jenkinsfile | opensearch-build/jenkins/gradle/
check-for-build.jenkinsfile | opensearch-build/jenkins/



</body>

</html>

**Comment by jordarlu** [comment]
Hi, Adding #2713 and #2714 to address test job for release-notes-check jenkinsfile. Thanks.

**Comment by jordarlu** [comment]
Hi, Adding https://github.com/opensearch-project/opensearch-build/issues/2722 and https://github.com/opensearch-project/opensearch-build/pull/2723 to address test job for whitesource-scan jenkinsfile. Thanks.

**Comment by jordarlu** [comment]
Hi, Adding #2789  and #2790 to addess test job for docker-build.jenkinsfile. thanks.

**Comment by jordarlu** [comment]
Hi, Adding https://github.com/opensearch-project/opensearch-build/issues/2791 and https://github.com/opensearch-project/opensearch-build/pull/2792 to addess test job for docker-build.jenkinsfile. thanks.
