### ISSUE TITLE
[META] Clean up flaky integ tests

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/opensearch-build#1531]
With the goal of running integ tests as part of the distribution build workflow, it's important the tests being ran are stable and consistent. Currently, there is a variety of integ test failures when running in Jenkins - some seem related to the plugin tests themselves, others seem related to the cluster / env setup in the Jenkins nodes. Using this meta issue to track and fix the different failures seen.

1.2.0 & 1.3.0:
- [x] AD plugin ([tracking issue](https://github.com/opensearch-project/anomaly-detection/issues/278))
- [x] Alerting plugin ([tracking issue](https://github.com/opensearch-project/alerting/issues/298))

Specific to 1.3.0:
- [x] ISM plugin ([tracking issue](https://github.com/opensearch-project/index-management/issues/258))
- [x] Async search ([tracking issue](https://github.com/opensearch-project/asynchronous-search/issues/90))

**Comment by ohltyler** [comment]
AD plugin:
```
Suite: Test class org.opensearch.ad.e2e.DetectionResultEvalutationIT
  2> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.ad.e2e.DetectionResultEvalutationIT.testDataset" -Dtests.seed=931C5320BF7E7812 -Dtests.security.manager=false -Dtests.locale=ar-YE -Dtests.timezone=Europe/Luxembourg -Druntime.java=14
  2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([931C5320BF7E7812:8144EBB842E381BD]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.opensearch.ad.e2e.DetectionResultEvalutationIT.verifyTestResults(DetectionResultEvalutationIT.java:104)
        at org.opensearch.ad.e2e.DetectionResultEvalutationIT.verifyAnomaly(DetectionResultEvalutationIT.java:86)
        at org.opensearch.ad.e2e.DetectionResultEvalutationIT.testDataset(DetectionResultEvalutationIT.java:60)
  2> NOTE: leaving temporary files on disk at: /tmp/tmpr2pvztp8/anomaly-detection/build/testrun/integTest/temp/org.opensearch.ad.e2e.DetectionResultEvalutationIT_931C5320BF7E7812-001
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=236, maxMBSortInHeap=6.791337600150323, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=ar-YE, timezone=Europe/Luxembourg
  2> NOTE: Linux 4.14.243-185.433.amzn2.aarch64 aarch64/AdoptOpenJDK 14.0.2 (64-bit)/cpus=16,threads=1,free=434384352,total=536870912
  2> NOTE: All tests run in this JVM: [AnomalyDetectorRestApiIT, HistoricalAnalysisRestApiIT, DetectionResultEvalutationIT]

66 tests completed, 1 failed, 1 skipped
```

**Comment by ohltyler** [comment]
Another flaky alerting integ test:
```
Suite: Test class org.opensearch.alerting.MonitorRunnerIT
  2> феб 01, 2022 12:44:17 AM org.opensearch.client.RestClient logResponse
  2> WARNING: request [PUT http://localhost:9200/.opendistro-anomaly-results-history-2020.10.17] returned 1 warnings: [299 OpenSearch-1.2.2-123d41ce4fad54529acd7a290efed848e707b624 "index name [.opendistro-anomaly-results-history-2020.10.17] starts with a dot '.', in the next major version, index names starting with a dot are reserved for hidden indices and system indices"]
  2> феб 01, 2022 12:44:18 AM org.opensearch.client.RestClient logResponse
  2> WARNING: request [PUT http://localhost:9200/.opendistro-anomaly-results-history-2020.10.17] returned 1 warnings: [299 OpenSearch-1.2.2-123d41ce4fad54529acd7a290efed848e707b624 "index name [.opendistro-anomaly-results-history-2020.10.17] starts with a dot '.', in the next major version, index names starting with a dot are reserved for hidden indices and system indices"]
  2> феб 01, 2022 12:44:22 AM org.opensearch.client.RestClient logResponse
  2> WARNING: request [PUT http://localhost:9200/.opendistro-anomaly-results-history-2020.10.17] returned 1 warnings: [299 OpenSearch-1.2.2-123d41ce4fad54529acd7a290efed848e707b624 "index name [.opendistro-anomaly-results-history-2020.10.17] starts with a dot '.', in the next major version, index names starting with a dot are reserved for hidden indices and system indices"]
  2> феб 01, 2022 12:44:24 AM org.opensearch.client.RestClient logResponse
  2> WARNING: request [PUT http://localhost:9200/.ewlydxmrjg] returned 1 warnings: [299 OpenSearch-1.2.2-123d41ce4fad54529acd7a290efed848e707b624 "index name [.ewlydxmrjg] starts with a dot '.', in the next major version, index names starting with a dot are reserved for hidden indices and system indices"]
  2> феб 01, 2022 12:44:25 AM org.opensearch.client.RestClient logResponse
  2> WARNING: request [PUT http://localhost:9200/.opendistro-anomaly-results-history-2020.10.17] returned 1 warnings: [299 OpenSearch-1.2.2-123d41ce4fad54529acd7a290efed848e707b624 "index name [.opendistro-anomaly-results-history-2020.10.17] starts with a dot '.', in the next major version, index names starting with a dot are reserved for hidden indices and system indices"]
  2> REPRODUCE WITH: ./gradlew ':alerting:integTest' --tests "org.opensearch.alerting.MonitorRunnerIT.test bucket-level monitor with acknowledged alert" -Dtests.seed=ACD4C7F5C8A5133D -Dtests.security.manager=false -Dtests.locale=sr -Dtests.timezone=PLT -Druntime.java=14
  2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([ACD4C7F5C8A5133D:A71CEF7486704F5B]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at org.opensearch.alerting.MonitorRunnerIT.verifyAlert(MonitorRunnerIT.kt:1600)
        at org.opensearch.alerting.MonitorRunnerIT.test bucket-level monitor with acknowledged alert(MonitorRunnerIT.kt:1128)
  2> NOTE: leaving temporary files on disk at: /tmp/tmpzgxjyrsk/alerting/alerting/build/testrun/integTest/temp/org.opensearch.alerting.MonitorRunnerIT_ACD4C7F5C8A5133D-001
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=991, maxMBSortInHeap=5.56516294962998, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=sr, timezone=PLT
  2> NOTE: Linux 4.14.243-185.433.amzn2.aarch64 aarch64/AdoptOpenJDK 14.0.2 (64-bit)/cpus=16,threads=1,free=349050224,total=536870912
  2> NOTE: All tests run in this JVM: [MonitorRunnerIT]

174 tests completed, 1 failed

=== Standard output of node `node{:alerting:integTest-0}` ===

FAILURE: Build failed with an exception.
```

**Comment by zelinh** [comment]
Close this now. This should have been fixed for 1.3.0.
