### ISSUE TITLE
[META] Create a lib tester for each library being used by the job

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#1712]
Create a lib tester and update the library tests for all existing libraries in `vars/` directory

### Libraries
- [ ] [archiveAssembleUpload.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/archiveAssembleUpload.groovy)
- [ ] [assembleManifest.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/assembleManifest.groovy)
- [ ] [assembleUpload.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/assembleUpload.groovy)
- [ ] [buildArchive.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/buildArchive.groovy)
- [ ] [buildAssembleUpload.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/buildAssembleUpload.groovy)
- [ ] [buildDockerImage.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/buildDockerImage.groovy)
- [ ] [buildManifest.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/buildManifest.groovy)
- [ ] [buildUploadManifestSHA.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/buildUploadManifestSHA.groovy)
- [ ] [createSha512Checksums.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/createSha512Checksums.groovy)
- [ ] [createSignatureFiles.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/createSignatureFiles.groovy)
- [ ] [detectDockerAgent.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/detectDockerAgent.groovy)
- [ ] [downloadBuildManifest.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/downloadBuildManifest.groovy)
- [ ] [getManifestSHA.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/getManifestSHA.groovy)
- [ ] [postCleanup.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/postCleanup.groovy)
- [x] [printArtifactDownloadUrlsForStaging.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/printArtifactDownloadUrlsForStaging.groovy)
- [ ] [promoteArtifacts.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/promoteArtifacts.groovy)
- [x] [publishNotification.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/publishNotification.groovy)
- [x] [runIntegTestScript.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/runIntegTestScript.groovy)
- [x] [uploadMinSnapshotsToS3.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/uploadMinSnapshotsToS3.groovy)
- [ ] [uploadArtifacts.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/uploadArtifacts.groovy)
- [x] [uploadTestResults.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/uploadTestResults.groovy)
- [x] [signArtifacts.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/signArtifacts.groovy)
- [x] [uploadToS3.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/uploadToS3.groovy)
- [x] [copyContainer.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/copyContainer.groovy)
- [x] [downloadFromS3.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/downloadFromS3.groovy)
- [x] [createReleaseTag.groovy](https://github.com/opensearch-project/opensearch-build/blob/main/vars/createReleaseTag.groovy)
- [ ] add ci check to make sure every file in var folder has a libTester associated with it

### Acceptance Criteria
- All existing libraries should have a lib tester associated with it
- All existing tests should be updated with libtesters

**Comment by jordarlu** [comment]
Thanks for the input and ticket!
By cross checking the libs in vars/ and test/jenkins/, we should have test for all 45 shared libs in vars/ except one .. 
will work on the remaining one, and we can close this ticket.

here is the list :

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/chunglu/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/chunglu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Column1 | libs (vars/) | test lib (tests/jenkins/)
-- | -- | --
1 | archiveAssembleUpload.groovy | TestArchiveAssembleUpload.groovy
2 | assembleManifest.groovy | TestAssembleManifest.groovy
3 | assembleUpload.groovy | TestAssembleUpload.groovy
4 | buildArchive.groovy | TestBuildArchive.groovy
5 | buildAssembleUpload.groovy | TestBuildAssembleUpload.groovy
6 | buildDockerImage.groovy | TestBuildDockerImage.groovy
7 | buildFailureMessage.groovy | TestBuildFailureMessage.groovy
8 | buildInfoYaml.groovy | TestBuildInfoYaml.groovy
9 | buildManifest.groovy | TestBuildManifest.groovy
10 | buildUploadManifestSHA.groovy | TestBuildUploadManifestSHA.groovy
11 | buildYumRepo.groovy | TestBuildYumRepo.groovy
12 | copyContainer.groovy | TestCopyContainer.groovy
13 | createGithubIssue.groovy | TestCreateGithubIssue.groovy
14 | createReleaseTag.groovy | TestCreateReleaseTag.groovy
15 | createSha512Checksums.groovy | PromoteArtifacts_actions_Jenkinsfile   (tests/jenkins/jobs/)
16 | createSignatureFiles.groovy | PromoteArtifacts_actions_Jenkinsfile (tests/jenkins/jobs/)
17 | createTestResultsMessage.groovy | TestCreateTestResultsMessage.groovy
18 | detectDockerAgent.groovy | DetectDockerImage_Jenkinsfile  (tests/jenkins/jobs/)
19 | detectTestDockerAgent.groovy | TestDetectTestDockerAgent.groovy
20 | downloadBuildManifest.groovy |  
21 | downloadFromS3.groovy | TestDownloadFromS3.groovy
22 | getManifestSHA.groovy | TestGetManifestSHA.groovy
23 | postCleanup.groovy | TestPostCleanup.groovy
24 | printArtifactDownloadUrlsForStaging.groovy | TestPrintArtifactDownloadUrlsForStaging.groovy
25 | promoteArtifacts.groovy | TestPromoteArtifacts.groovy
26 | promoteContainer.groovy | TestPromoteContainer.groovy
27 | promoteYumRepos.groovy | TestPromoteYumRepos.groovy
28 | publishNotification.groovy | TestPublishNotification.groovy
29 | rpmCommands.groovy | invoked by   rpmDistValidation.groovy
30 | rpmDashboardsDistValidation.groovy | TestRpmDashboardsDistValidation.groovy
31 | rpmDistValidation.groovy | Shell   script
32 | rpmMetaValidation.groovy | TestRpmMetaValidation.groovy
33 | rpmOpenSearchDistValidation.groovy | TestRpmOpenSearchDistValidation.groovy
34 | runBwcTestScript.groovy | TestRunBwcTestScript.groovy
35 | runGradleCheck.groovy | TestRunGradleCheck.groovy
36 | runIntegTestScript.groovy | TestRunIntegTestScript.groovy
37 | runPerfTestScript.groovy | TestRunPerfTestScript.groovy
38 | scanDockerImage.groovy | TestScanDockerImage.groovy
39 | signArtifacts.groovy | TestSignArtifacts.groovy
40 | systemdCommands.groovy | invoked by rpmDistValidation.groovy and   rpmOpenSearchDistValidation.groovy
41 | uploadArtifacts.groovy | invoked by   assembleUpload.groovy
42 | uploadIndexFile.groovy | TestUploadIndexFile.groovy
43 | uploadMinSnapshotsToS3.groovy | TestUploadMinSnapshotsToS3.groovy
44 | uploadTestResults.groovy | TestUploadTestResults.groovy
45 | uploadToS3.groovy | TestUploadToS3.groovy



</body>

</html>

**Comment by prudhvigodithi** [comment]
Hey @jordarlu thanks for the list, I can see a lib-tester for [downloadBuildManifest](https://github.com/opensearch-project/opensearch-build/blob/main/tests/jenkins/lib-testers/DownloadBuildManifestLibTester.groovy), and this has been used at [multiple tests](https://github.com/opensearch-project/opensearch-build/search?q=downloadBuildManifest), do indirectly looks to me like this has been tested ;), @gaiksaya @peterzhuamazon @zelinh @bbarani  please add your thoughts and can we proceed to close this?

**Comment by jordarlu** [comment]
thank you @prudhvigodithi , looks good to close this ticket to me now!! and move on to #1468

**Comment by zelinh** [comment]
I think the list you provided is for the jenkins tests but not for the lib-testers. All lib testers are located in this [folder](https://github.com/opensearch-project/opensearch-build/tree/main/tests/jenkins/lib-testers).

**Comment by prudhvigodithi** [comment]
Hey @zelinh the lib-testers are internally used to test the jenkins shared libs, to idea here is to assert that each shared library has some testing involved.

**Comment by zelinh** [comment]
> Hey @zelinh the lib-testers are internally used to test the jenkins shared libs, to idea here is to assert that each shared library has some testing involved.

I see what you said. I thought this issue is to enforce that we would need lib-tester for all the libraries in addition to the unit tests. I agree we could mainly focus on #1468 and not worry too much about this issue.
