### ISSUE TITLE
Build bundle 1.1-SNAPSHOT

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#179]
Support for passing `--snapshot` was added in #189. Assuming build works in #212. 

Fix snapshot builds in plugins, and change the plugin CI to build snapshot versions by default:

- [x] https://github.com/opensearch-project/common-utils/issues/56
fixed in https://github.com/opensearch-project/common-utils/pull/58
- [x] https://github.com/opensearch-project/sql/issues/177
fixed in https://github.com/opensearch-project/sql/pull/181
- [x] https://github.com/opensearch-project/alerting/issues/141
fixed in https://github.com/opensearch-project/alerting/pull/142
- [x] https://github.com/opensearch-project/index-management/issues/116
fixed in https://github.com/opensearch-project/index-management/pull/121
- [x] https://github.com/opensearch-project/k-NN/issues/78
fixed in https://github.com/opensearch-project/k-NN/pull/79
- [x] https://github.com/opensearch-project/security/issues/1403
fixed in https://github.com/opensearch-project/security/pull/1409
- [x] https://github.com/opensearch-project/anomaly-detection/issues/173
fixed in https://github.com/opensearch-project/anomaly-detection/pull/176
- [x] https://github.com/opensearch-project/asynchronous-search/issues/30
fixed in https://github.com/opensearch-project/asynchronous-search/pull/31
- [x] https://github.com/opensearch-project/dashboards-reports/issues/138
fixed in https://github.com/opensearch-project/dashboards-reports/pull/140
- [x] https://github.com/opensearch-project/dashboards-notebooks/issues/60
fixed in https://github.com/opensearch-project/dashboards-notebooks/pull/62
- [x] notifications
fixed in https://github.com/opensearch-project/notifications/pull/284
- [x] https://github.com/opensearch-project/performance-analyzer-rca/issues/48
fixed in https://github.com/opensearch-project/performance-analyzer-rca/pull/54
fixed in https://github.com/opensearch-project/performance-analyzer-rca/pull/47
fixed in https://github.com/opensearch-project/performance-analyzer-rca/pull/55
- [x] https://github.com/opensearch-project/performance-analyzer/issues/43
fixed in https://github.com/opensearch-project/performance-analyzer/pull/53
- [x] #349

**Comment by dblock** [comment]
Support for flags added in #189.

Actual snapshot builds broken:

- [ ] https://github.com/opensearch-project/sql/issues/177
- [ ] https://github.com/opensearch-project/index-management/issues/116
- [ ] https://github.com/opensearch-project/k-NN/issues/78
- [ ] https://github.com/opensearch-project/security/issues/1403

**Comment by dblock** [comment]
After all the subtasks are fixed we still need to hook up Jenkins workflow or modify the one in #291 to build the snapshot daily.

**Comment by dblock** [comment]
https://github.com/opensearch-project/opensearch-build/pull/360 is the last issue

**Comment by dblock** [comment]
All done, closing!
