### ISSUE TITLE
Build 1.0.1 bundle end-to-end daily

### ISSUE THREAD

**Issue by mch2** [opensearch-project/opensearch-build#195]
Rename [1.0 manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/opensearch-1.0.0.yml) to 1.0.1 and kick off automation daily.

Meta issue of bundle building end-to-end with all its related remaining work.

- [x] https://github.com/opensearch-project/opensearch-build/issues/148
- [x] https://github.com/opensearch-project/opensearch-build/issues/149
- [x] https://github.com/opensearch-project/opensearch-build/issues/200
- [ ] https://github.com/opensearch-project/opensearch-build/issues/153
- [x] https://github.com/opensearch-project/opensearch-build/issues/135
- [x] https://github.com/opensearch-project/opensearch-build/issues/113

**Comment by dblock** [comment]
While some automation is being used now, we punted on running end-to-end for 1.0.1. cc: @peterzhuamazon if you think otherwise.
