### ISSUE TITLE
Build test Darwin version of min OpenSearch distribution to support plugin testing on MacOS.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#2216]
### Is your feature request related to a problem? Please describe
For k-NN, to run integ tests on Mac is not compatible.
KNN uses lang painless to inject scripts. To test on MacOS right now the options are `INTEG_TEST`, which will bring up a cluster with plain and no modules (mainly lang painless) except [transportModulesFiles](https://github.com/opensearch-project/OpenSearch/blob/main/distribution/archives/build.gradle) 
Second option is to use `ARCHIVE` which will allow direct download of zip and test bringing up the cluster, which looks for darwin zip, which is not available for testing.

https://github.com/opensearch-project/OpenSearch/issues/1676

### Describe the solution you'd like

- [x]  Test the existing [build_workflow](https://github.com/opensearch-project/opensearch-build/tree/main/src/build_workflow) to run the OpenSearch build with platform as `darwin`.
https://github.com/opensearch-project/opensearch-build/issues/2350
- [x] Run the existing [distribution build job](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile) on MacOS ec2 agent which outputs the min distribution of OpenSearch of type Darwin.
https://github.com/opensearch-project/opensearch-build/issues/2361
- [x] Build a Mac ec2 AMI able to execute [build_workflow](https://github.com/opensearch-project/opensearch-build/tree/main/src/build_workflow) and [assemble_workflow](https://github.com/opensearch-project/opensearch-build/tree/main/src/assemble_workflow) that can generate OpenSrearch min distribution.
https://github.com/opensearch-project/opensearch-ci/issues/163
- [x] Automate the Mac jenkins agents creation and add to [Public Jenkins](https://build.ci.opensearch.org/).
https://github.com/opensearch-project/opensearch-ci/issues/157
- [x] Add required missing packages to MacOS agents, that support signing workflow, to sign and upload darwin artifacts
https://github.com/opensearch-project/opensearch-build/issues/2375
- [x] MacOS agents support default `/bin/bash`, remove `nodeProperties` in CDK code and allow jenkins to use default `PATH` part of `AMI`.
https://github.com/opensearch-project/opensearch-ci/issues/174
- [x] Validate the darwin artifacts built using the [distribution-build job](https://build.ci.opensearch.org/job/distribution-build-opensearch/).
[Jenkins build Mac 2.2.0-SNAPSHOT](https://build.ci.opensearch.org/job/distribution-build-opensearch/5834/)

### Describe alternatives you've considered

Other alternatives is to test on Linux, Docker but this requires developers with MacOs to setup alternative virtual machines to test the plugins.

### Additional context

https://github.com/opensearch-project/opensearch-build/issues/38#issuecomment-944373452

### Acceptance Criteria 

- Test using the existing assemble task from OpenSearch `distribution:archives:darwin-arm64-tar:assemble` to build the darwin min distribution, integrate with build workflow to automate the  min distribution creation.
- Test with cross compile framework to build darwin min distribution with existing build workflow.
- Approach to be considered: directly run the build workflow on mac ec2 instance that has supported architecture `MACHTYPE=x86_64`

**Comment by jmazanec15** [comment]
Hi @prudhvigodithi and @bbarani, how much effort will this take to do/what release will this be targeted for? Do we already have support for MacOS ec2 agent's? Are there any tasks on this I could pick up?

**Comment by prudhvigodithi** [comment]
Hey we have development version Darwin `min` artifact out for testing, use the following URL as reference to download the Darwin min artifact.
https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.1.1/latest/darwin/x64/tar/builds/opensearch/dist/opensearch-min-2.1.1-darwin-x64.tar.gz
@jmazanec15 can you please test and post your findings here?
Thank you 
@bbarani

**Comment by jmazanec15** [comment]
Thanks @prudhvigodithi!

When running:
```
./gradlew build 
...
> Task :integTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTest'.
> Could not resolve all files for configuration ':opensearch_distro_extracted_testclusters--integTest-0-2.1.1-SNAPSHOT-'.
   > Could not resolve opensearch-distribution-snapshot:opensearch:2.1.1-SNAPSHOT.
     Required by:
         project :
      > Could not resolve opensearch-distribution-snapshot:opensearch:2.1.1-SNAPSHOT.
         > Could not get resource 'https://artifacts.opensearch.org/snapshots/core/opensearch/2.1.1-SNAPSHOT/opensearch-min-2.1.1-SNAPSHOT-darwin-x64-latest.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/snapshots/core/opensearch/2.1.1-SNAPSHOT/opensearch-min-2.1.1-SNAPSHOT-darwin-x64-latest.tar.gz'. Received status code 403 from server: Forbidden
```

However, when downloading custom url and using it, it works:

**Comment by jmazanec15** [comment]
> However, when downloading custom url and using it, it appears to work (will confirm in about 20 min - accidentally posted comment too soon):
./gradlew build -PcustomDistributionUrl=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.1.1/latest/darwin/x64/tar/builds/opensearch/dist/opensearch-min-2.1.1-darwin-x64.tar.gz
...

Confirmed build was successful!

Is it possible to publish artifact to "https://artifacts.opensearch.org" instead of "https://ci.opensearch.org" so that we dont have to pass -PcustomDistributionUrl flag for building? For opensearchplugin, ARCHIVE defaults to "https://artifacts.opensearch.org"

**Comment by prudhvigodithi** [comment]
We now have the darwin min snapshot artifacts accessible via https://artifacts.opensearch.org/, the default URL used in OpenSearch.

[Jenkins build Mac 2.2.0-SNAPSHOT](https://build.ci.opensearch.org/job/distribution-build-opensearch/5834/)
https://artifacts.opensearch.org/snapshots/core/opensearch/2.2.0-SNAPSHOT/opensearch-min-2.2.0-SNAPSHOT-darwin-x64-latest.tar.gz

[Jenkins build Mac 2.1.1-SNAPSHOT](https://build.ci.opensearch.org/job/distribution-build-opensearch/5836/console)
https://artifacts.opensearch.org/snapshots/core/opensearch/2.1.1-SNAPSHOT/opensearch-min-2.1.1-SNAPSHOT-darwin-x64-latest.tar.gz

**Comment by prudhvigodithi** [comment]
> Is it possible to publish artifact to "https://artifacts.opensearch.org" instead of "https://ci.opensearch.org" so that we dont have to pass -PcustomDistributionUrl flag for building? For opensearchplugin, ARCHIVE defaults to "https://artifacts.opensearch.org"

Hey We now have the darwin min snapshot artifacts accessible via https://artifacts.opensearch.org/, the default URL used in OpenSearch.

[Jenkins build Mac 2.2.0-SNAPSHOT](https://build.ci.opensearch.org/job/distribution-build-opensearch/5834/)
https://artifacts.opensearch.org/snapshots/core/opensearch/2.2.0-SNAPSHOT/opensearch-min-2.2.0-SNAPSHOT-darwin-x64-latest.tar.gz

[Jenkins build Mac 2.1.1-SNAPSHOT](https://build.ci.opensearch.org/job/distribution-build-opensearch/5836/console)
https://artifacts.opensearch.org/snapshots/core/opensearch/2.1.1-SNAPSHOT/opensearch-min-2.1.1-SNAPSHOT-darwin-x64-latest.tar.gz

**Comment by prudhvigodithi** [comment]
> > Is it possible to publish artifact to "https://artifacts.opensearch.org" instead of "https://ci.opensearch.org" so that we dont have to pass -PcustomDistributionUrl flag for building? For opensearchplugin, ARCHIVE defaults to "https://artifacts.opensearch.org"
> 
> Hey We now have the darwin min snapshot artifacts accessible via https://artifacts.opensearch.org/, the default URL used in OpenSearch.
> 
> [Jenkins build Mac 2.2.0-SNAPSHOT](https://build.ci.opensearch.org/job/distribution-build-opensearch/5834/) https://artifacts.opensearch.org/snapshots/core/opensearch/2.2.0-SNAPSHOT/opensearch-min-2.2.0-SNAPSHOT-darwin-x64-latest.tar.gz
> 
> [Jenkins build Mac 2.1.1-SNAPSHOT](https://build.ci.opensearch.org/job/distribution-build-opensearch/5836/console) https://artifacts.opensearch.org/snapshots/core/opensearch/2.1.1-SNAPSHOT/opensearch-min-2.1.1-SNAPSHOT-darwin-x64-latest.tar.gz

@jmazanec15 when you get a chance can you please test and update?
Thank you

**Comment by saratvemulapalli** [comment]
Thanks @prudhvigodithi, this is amazing . I happen to work with AD plugin and it works!!

```
vemsarat@3c22fb88f11c anomaly-detection % 
vemsarat@3c22fb88f11c anomaly-detection % ./gradlew build                                                                                                                                                                                 
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Mac OS X 10.16 (x86_64)
  JDK Version           : 14 (Oracle JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home
  Random Testing Seed   : 3D7474600A5D2F17
  In FIPS 140 mode      : false
=======================================

> Task :compileJava
Note: /Users/vemsarat/Desktop/workspace/Code/anomaly-detection/src/main/java/org/opensearch/ad/ml/EntityColdStarter.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/vemsarat/Desktop/workspace/Code/anomaly-detection/src/main/java/org/opensearch/ad/task/ADBatchTaskRunner.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
<==========---> 79% EXECUTING [30s]
> :integTest > Resolve files of :opensearch_distro_extracted_testclusters--integTest-0-2.1.1-SNAPSHOT- > opensearch-min-2.1.1-SNAPSHOT-darwin-x64-latest.tar.gz > 141.9 MiB/209.5 MiB downloaded
```

**Comment by prudhvigodithi** [comment]
> Thanks @prudhvigodithi, this is amazing . I happen to work with AD plugin and it works!!

Thanks for testing @saratvemulapalli ;)

**Comment by Arpit-Bandejiya** [comment]
Hi @prudhvigodithi  while trying to build async-search for 3.0.0 in mac I'm facing the below error:

```
abandeji@bcd074462b7f asynchronous-search % ./gradlew build -PcustomDistributionUrl=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/darwin/x64/tar/builds/opensearch/dist/opensearch-min-3.0.0-darwin-x64.tar.gz
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.4.2
  OS Info               : Mac OS X 13.2.1 (aarch64)
  JDK Version           : 17 (Amazon Corretto JDK)
  JAVA_HOME             : /Users/abandeji/.sdkman/candidates/java/17.0.6-amzn
  Random Testing Seed   : 9DCE0F0910A72E66
  In FIPS 140 mode      : false
=======================================
> Task :integTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTest'.
> Could not resolve all files for configuration ':opensearch_distro_extracted_testclusters--integTest-0-3.0.0-SNAPSHOT-'.
   > Could not resolve opensearch-distribution-snapshot:opensearch:3.0.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve opensearch-distribution-snapshot:opensearch:3.0.0-SNAPSHOT.
         > Could not get resource 'https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/latest/darwin/x64/tar/builds/opensearch/dist/opensearch-min-3.0.0-darwin-x64.tar.gz'.
            > Could not HEAD 'https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.0.0/7106/darwin/x64/tar/builds/opensearch/dist/opensearch-min-3.0.0-darwin-x64.tar.gz'. Received status code 403 from server: Forbidden

````

Is there a way to check the url is correct or not? I'm not able to visit the base ci.opensearch.org as well since it says forbidden on browser.

**Comment by prudhvigodithi** [comment]
Hey @Arpit-Bandejiya the URL is as follows 
https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-darwin-x64-latest.tar.gz
Also if you are by default using a mac workspace the default pulled should be a darwin min. All the snapshots are stored in `artifacts.opensearch.org`, so if you still want to use `-PcustomDistributionUrl` then the command is as follows
```
./gradlew build -PcustomDistributionUrl=https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-darwin-x64-latest.tar.gz
```
Please try with this and let me know.
Thank you

**Comment by Arpit-Bandejiya** [comment]
This works @prudhvigodithi  thanks!

**Comment by Arpit-Bandejiya** [comment]
@prudhvigodithi I have one question though when I build it without passing this flag, I get this error:
```
* What went wrong:
Execution failed for task ':integTest'.
> Could not resolve all files for configuration ':opensearch_distro_extracted_testclusters--integTest-0-3.0.0-SNAPSHOT-'.
   > Could not resolve opensearch-distribution-snapshot:opensearch:3.0.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve opensearch-distribution-snapshot:opensearch:3.0.0-SNAPSHOT.
         > Could not get resource 'https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-darwin-arm64-latest.tar.gz'.
            > Could not HEAD 'https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-darwin-arm64-latest.tar.gz'. Received status code 403 from server: Forbidden
```
As can be seen the url is same as one we passed in command line. Any possible reason of this failing?

**Comment by prudhvigodithi** [comment]
Hey @Arpit-Bandejiya We are publishing darwin `x64`, the URL is not same if you notice it is going to `arm64` (from your screenshot `opensearch-min-3.0.0-SNAPSHOT-darwin-arm64-latest.tar.gz`)

Sample Download URL:
https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-darwin-x64-latest.tar.gz

Mac os support `x86_64` and `arm64` as well, mac m1 works for both `x86_64` and `arm64` with help of Rosetta 2
`arm64` is the architecture used by newer Macs built on Apple Silicon, shipped in late 2020 and beyond, but `x64` should work as well, `pgrep oahd` should output the Rosetta process

Useful blog's:
https://eclecticlight.co/2021/01/22/running-intel-code-on-your-m1-mac-rosetta-2-and-oah/
https://docs.elementscompiler.com/Platforms/Cocoa/CpuArchitectures/#:~:text=On%20macOS%2C%20two%20architecture%20are,in%20late%202020%20and%20beyond.

So in your case please use `-PcustomDistributionUrl`.
