### ISSUE TITLE
[Meta] Create UI dashboards to view the build, test and release stats

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#2297]
### Is your feature request related to a problem? Please describe

We currently do not have any dashboards to view the status of builds, tests and releases for OpenSearch and OpenSearch dashboard artifacts.

### Describe the solution you'd like

**Build, release and test Dashboards  (OpenSearch and OpenSearch Dashboards)**

- Integrate and display build time, PR’s, CVE’s, integration / BWC tests results corresponding to every distribution build(s) for all supported versions
- Link Performance results stats for distribution builds
- Display the performance stats along with highlighting anomalies for  distribution build(s) for all supported versions
- Add ability to download snapshot artifacts generated through distribution build process directly from the dashboard page 

### Architectural Diagram
![Untitled drawio (1)](https://user-images.githubusercontent.com/44730413/188994033-8922370c-e544-4237-a579-9ba6427618c4.png)
.jpg)

### Implementation

- [x] [Reduce API calls on main page from 30+ to 1](https://github.com/opensearch-project/opensearch-build/issues/2391)
- [x] [Use commits.yml to fetch commits per build/PR](https://github.com/opensearch-project/opensearch-build/issues/2392)
  - https://github.com/opensearch-project/opensearch-build/issues/2410
- [x] [Create Commits page](https://github.com/opensearch-project/opensearch-build/issues/2393)
- [x] [Create Integ test page](https://github.com/opensearch-project/opensearch-build/issues/2394)
- [ ] [Create BWC test page](https://github.com/opensearch-project/opensearch-build/issues/2395)
- [x] [Create Perf test page](https://github.com/opensearch-project/opensearch-build/issues/2396)
- [x] [Create CVE page](https://github.com/opensearch-project/opensearch-build/issues/2397)
- [ ] Start time display on dashboard

#### P0 (POC) :
- [x] Users can view current status of distribution build along with build stats
- [x] Users can download the distribution build artifacts directly from the dashboard
- [x] Users can view PR details corresponding to a build
- [x] Users can view CVE information corresponding to a build
- [x]  Users can view integration test stats corresponding to a build
- [x] Users can view performance test stats corresponding to a build
- [ ] Users can view BWC test stats corresponding to a build

**Comment by bbarani** [comment]
This is the subset of https://github.com/opensearch-project/opensearch-build/issues/2080

**Comment by bbarani** [comment]
Test publisher info can be reference from https://github.com/opensearch-project/opensearch-build/pull/938

**Comment by bshien** [comment]
- [ ] Reduce API calls on main page from 30+ to 1
- [ ] Use commits.yml to fetch commits per build/PR
- [ ] Create Commits page
- [ ] Create Integ test page
- [ ] Create BWC test page
- [ ] Create Perf test page
- [ ] Create CVE page
