### ISSUE TITLE
Documentation meta issue

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#2493]
As in case of any project documentation is critical and should be added as well as maintained as the project progress. Listing few points that needs to be added as a part of the documentation: 

- [ ] Onboarding to universal release mechanism
- [ ] How remote repositories should add ci checks for their JenkinsFiles
- [ ]  Determine the smallest size a workflow can be to limit the number of practices that need to be enforced
- [ ] https://github.com/opensearch-project/opensearch-build/issues/1607
- [ ] Component: Each component should have a [RELEASING.md](https://github.com/opensearch-project/opensearch-java/blob/main/RELEASING.md) file documenting how to release the artifact
- [ ] Release system: The opensearch-build repo should have details about developing and working on jenkinsFiles and libraries. To be added in [DEVELOPER_GUIDE.md](https://github.com/opensearch-project/opensearch-build/blob/main/DEVELOPER_GUIDE.md)
