### ISSUE TITLE
Inventory and create library functions for common functionality

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#2505]
- [x] opensearch-project/opensearch-build#2637
- [x] https://github.com/opensearch-project/opensearch-build/issues/2398
- [x] https://github.com/opensearch-project/opensearch-build-libraries/pull/127
- [x] opensearch-project/opensearch-build#2839
- [x] opensearch-project/opensearch-build#2857
- [x] opensearch-project/opensearch-build#2965
~- [ ] publishToDockerHub~ We already have a CopyContainer library that can be used to publish to docker or ECR
~- [ ] publishToECR~
- [x] opensearch-project/opensearch-build-libraries#155
- [ ] opensearch-project/opensearch-build-libraries#154
- [ ] More to add if any.

**Comment by prudhvigodithi** [comment]
Client   Universal Release process (ETA)
opensearch-py-ml    November 15th, 2022
opensearch-py          November 15th, 2022
Java                            November 30th, 2022

**Comment by gaiksaya** [comment]
Closing this issue as all tasks are complete. For packagist we do not need to add a library as it is directly integrated with GitHub.
