### ISSUE TITLE
[Campaign] `opensearch.opensearchplugin` add `groupID` field to `org.opensearch.plugin`

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build#2521]
### Is your feature request related to a problem? Please describe

Main Related issue: https://github.com/opensearch-project/OpenSearch/pull/4156
Track the plugins to make sure the `groupId` is added as `org.opensearch.plugin` to the publication `pluginZip` inside the `build.gradle` file.

- [x] [opensearch-plugin-template-java](https://github.com/opensearch-project/opensearch-plugin-template-java/issues/34)
- [x] [alerting](https://github.com/opensearch-project/alerting/issues/533)
- [x] [anomaly-detection](https://github.com/opensearch-project/anomaly-detection/issues/646)
- [x] [asynchronous-search](https://github.com/opensearch-project/asynchronous-search/issues/172)
- [x] [common-utils](https://github.com/opensearch-project/common-utils/issues/226)
- [x] [dashboards-reports](https://github.com/opensearch-project/dashboards-reports/issues/439)
- [x] [index-management](https://github.com/opensearch-project/index-management/issues/479)
- [x] [job-scheduler](https://github.com/opensearch-project/job-scheduler/issues/225)
- [x] [k-NN](https://github.com/opensearch-project/k-NN/issues/520)
- [x] [performance-analyzer](https://github.com/opensearch-project/performance-analyzer/issues/259)
- [x] [performance-analyzer-rca](https://github.com/opensearch-project/performance-analyzer-rca/issues/222)
- [x] [security](https://github.com/opensearch-project/security/issues/2055)
- [x] [sql](https://github.com/opensearch-project/sql/issues/790)
- [x] [observability](https://github.com/opensearch-project/observability/issues/972)
- [x] [cross-cluster-replication](https://github.com/opensearch-project/cross-cluster-replication/issues/534)
- [x] [ml-commons](https://github.com/opensearch-project/ml-commons/issues/412)
- [x] [geospatial](https://github.com/opensearch-project/geospatial/issues/131)
- [x] [notifications](https://github.com/opensearch-project/notifications/issues/514)

Documentation Update: https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip

- [x] [opensearch-plugins](https://github.com/opensearch-project/opensearch-plugins/issues/162): Update the document [BUILDING.md](https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip) to reflect the new changes.

### Describe the solution you'd like

Solution Implemented from the PR https://github.com/opensearch-project/OpenSearch/pull/4156

### Describe alternatives you've considered

N/A

### Additional context

More Background about publishing plugin zips to maven: https://github.com/opensearch-project/opensearch-build/issues/1916
More Background on extending `opensearch.pluginzip` to the 3rd party plugins: https://github.com/opensearch-project/OpenSearch/issues/3692

**Comment by prudhvigodithi** [comment]
Adding @lukas-vlcek @dblock @bbarani

**Comment by lukas-vlcek** [comment]
@prudhvigodithi Is there any way how I can help with 2.4 pack-porting?

I think all the individual plugin PRs have already been created and they are now waiting for review/merge. Once they are merged they will all need to be back-ported to `2.x` branch before `2.4` branch is created, right? The pack-port labels are also created at this point. Is there anything I can help with?

**Comment by prudhvigodithi** [comment]
Hey @lukas-vlcek Just noticed this error with [notifications-core](https://github.com/opensearch-project/notifications/pull/549#issuecomment-1278186297) when executing `./gradlew publishToMavenLocal `  (coming from [build script](https://github.com/opensearch-project/opensearch-build/blob/main/scripts/components/notifications-core/build.sh#L73))
I have raised the [PR](https://github.com/opensearch-project/notifications/pull/554) to add `startParameter.excludedTaskNames=["publishPluginZipPublicationToMavenLocal"]`, to fix the error `org.gradle.api.publish.maven.InvalidMavenPublicationException:`
adding @reta

**Comment by lukas-vlcek** [comment]
Please see my comment here: https://github.com/opensearch-project/notifications/pull/554#issuecomment-1279367613

**Comment by prudhvigodithi** [comment]
Hey @lukas-vlcek when you get a chance can you please do Documentation Update for your changes?
https://github.com/opensearch-project/opensearch-plugins/blob/main/BUILDING.md#opensearchpluginzip

**Comment by lukas-vlcek** [comment]
@prudhvigodithi Please see https://github.com/opensearch-project/opensearch-plugins/pull/175

**Comment by prudhvigodithi** [comment]
Closing this issue as all the associated tasks are completed. @lukas-vlcek @bbarani @peterzhuamazon

**Comment by jmazanec15** [comment]
Ah looks like its related to https://github.com/opensearch-project/notifications/pull/554#issuecomment-1282280470.
