### ISSUE TITLE
[META] RPM, Deb and Windows integration testing lacks jenkins automation

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#2994]
### Describe the bug

Currently, we are running integration tests manually on windows and other distributions since the process is not automated yet. 
Looks like the test workflow already has the required support for them but needs to be automated in terms of CI or Jenkins. 

### To reproduce

Need to create a VM and then run IT on that for all components. It is much more complicated for OSD

### Expected behavior

The integration testing should be automated to save human hours. 

### Sub tasks
- [ ] Create integration test job per distribution type
    1. Currently we have automated integration test job for TAR only
- [ ] Support `—component` parameter to OpenSearch Dashboards functional tests execution
    1. This is required to execute tests in [parallel](https://github.com/opensearch-project/opensearch-build/issues/2144) + Execute tests for specific plugin(s)
- [ ] Report, surface test failures along with logs ( including cluster logs ) via appropriate channel (GitHub, slack etc..)
- [x] https://github.com/opensearch-project/opensearch-build/issues/3156 @peterzhuamazon 
- [x] https://github.com/opensearch-project/opensearch-build/issues/3190 @peterzhuamazon 
- [x] https://github.com/opensearch-project/opensearch-build/issues/3198 @peterzhuamazon 
- [ ] https://github.com/opensearch-project/opensearch-build/issues/3243 @peterzhuamazon 
- [ ] https://github.com/opensearch-project/opensearch-build/issues/3196 @peterzhuamazon 
- [ ] https://github.com/opensearch-project/opensearch-build/issues/3432 @peterzhuamazon 
- [x] https://github.com/opensearch-project/opensearch-build-libraries/issues/197 @peterzhuamazon 
- [ ] https://github.com/opensearch-project/opensearch-build/pull/3316#discussion_r1176902722 @Divyaasm 
  * https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/644
  * https://github.com/opensearch-project/opensearch-build/issues/3476
- [x] https://github.com/opensearch-project/opensearch-build/issues/3461
- [ ] Execute integration tests at nightly cadence ( Along from release level tests )
- [ ] Add necessary tests for all Jenkins files

### Acceptance Criteria
- [ ] Integration tests should run via test_workflow (python framework) with jenkins as a wrapper
- [ ] Integration tests should run on all supported platforms (eg: tar, rpm and deb running on linux)
- [ ] The workflow should run independently on any workflow. Distribution workflow should not be blocked just because integration testing is taking a long time.
- [ ] Integration test failures should create GH issues on respective GH repos similar to [build failure issue](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3030)

**Comment by peterzhuamazon** [comment]
Related to 
* https://github.com/opensearch-project/opensearch-build/issues/1951
* https://github.com/opensearch-project/opensearch-build/issues/2308

**Comment by peterzhuamazon** [comment]
I would rename this issue to Jenkins automation, as they both have the Python code automation completed, tho with bugs.

Thanks.

**Comment by gaiksaya** [comment]
Sure. Do you know the bugs @peterzhuamazon ?

**Comment by bbarani** [comment]
@gaiksaya @peterzhuamazon Lets make sure we close the gap for Debian distribution as well.

**Comment by peterzhuamazon** [comment]
* https://github.com/opensearch-project/opensearch-build/issues/3156

**Comment by bbarani** [comment]
@peterzhuamazon https://github.com/opensearch-project/opensearch-build/issues/2144

**Comment by peterzhuamazon** [comment]
New issue:
* #3190 
* #3191

**Comment by peterzhuamazon** [comment]
* #3198

**Comment by bbarani** [comment]
@zelinh Can you provide an update here?

**Comment by peterzhuamazon** [comment]
Windows integTest is completed with windows container here:
* https://github.com/opensearch-project/opensearch-ci/issues/281

**Comment by peterzhuamazon** [comment]
This means RPM/DEB/Windows all have integration Test today.

**Comment by peterzhuamazon** [comment]
Close this issue now as it will be handled in the above issue for Windows.

**Comment by peterzhuamazon** [comment]
* https://github.com/opensearch-project/opensearch-build-libraries/pull/308
* https://github.com/opensearch-project/opensearch-build/pull/4023
* https://github.com/opensearch-project/opensearch-build-libraries/pull/314
* https://github.com/opensearch-project/opensearch-build/pull/4027

**Comment by gaiksaya** [comment]
I think this issue was more for automation related part. This PR should add it now.https://github.com/opensearch-project/opensearch-build/pull/4368
