### ISSUE TITLE
[META] Move snapshot build jobs out of distribution build jobs

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#3185]
## Problem:

Currently the snapshot jobs are tightly coupled with monolithic distribution build job creating single point of failure and bottleneck for day to day development. 
There are 2 kinds of snapshots:
1. Min tarball snapshot: This is core/engine/min only snapshot available as a tarball and accessible via https://artifacts.opensearch.org/snapshots/core/opensearch/....
More details: https://github.com/opensearch-project/opensearch-build#min-snapshots
2. Maven snapshots: These are the snapshots published on nexus accessible via https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/ and includes all components including plugins.

  1) is not an issue today and is independent of any components. However, 2) is a tightly coupled workflow. 
The maven snapshots are published based on input manifest where if one of the component fails to build, the entire snapshot publication to maven is abandoned. We will need to move the snapshot job outside of distribution build jobs in to its own job / have the respective repos publish snapshots via GitHub actions to de-centralize the publishing process.

## Solution
The move tightly coupled workflows can be decoupled by moving snapshot publication to each component repository. The credentials to publish snapshot can be retrieved via AWS GHA integration that is already set in place 

We tried this solution with security plugin and it works well. https://github.com/opensearch-project/security/actions/runs/4206453061

Child issues with all backend plugins:

- [x] https://github.com/opensearch-project/OpenSearch/issues/6365
- [x] https://github.com/opensearch-project/alerting/issues/802
- [x] https://github.com/opensearch-project/anomaly-detection/issues/813
- [x] https://github.com/opensearch-project/asynchronous-search/issues/239
- [x] https://github.com/opensearch-project/index-management/issues/689
- [x] https://github.com/opensearch-project/job-scheduler/issues/319
- [x] https://github.com/opensearch-project/k-NN/issues/771
- [x] https://github.com/opensearch-project/performance-analyzer/issues/385
- [x] https://github.com/opensearch-project/sql/issues/1358
- [x] https://github.com/opensearch-project/observability/issues/1414
- [x] https://github.com/opensearch-project/notifications/issues/620
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/710
- [x] https://github.com/opensearch-project/common-utils/issues/361
- [x] https://github.com/opensearch-project/reporting/issues/648
- [x] https://github.com/opensearch-project/ml-commons/issues/734
- [x] https://github.com/opensearch-project/geospatial/issues/225
- [x] https://github.com/opensearch-project/security-analytics/issues/334
- [x] https://github.com/opensearch-project/neural-search/issues/114
- [x] https://github.com/opensearch-project/security/pull/2438
- [x] https://github.com/opensearch-project/opensearch-testcontainers/issues/75

**Comment by gaiksaya** [comment]
Related #1182

**Comment by jordarlu** [comment]
The plan is to move the snapshot to each individual repo
