### ISSUE TITLE
[META] Publish OpenSearch and OpenSearch Dashboards images to Amazon public ECR gallery

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#320]
**Is your feature request related to a problem? Please describe.**
Currently the OpenSearch and OpenSearch Dashboards bundle images are published only on DockerHub. Customers face throttling issue sometimes on DockerHub.

**Describe the solution you'd like**
Make the below Docker images available on public [ECR repos](https://gallery.ecr.aws/)  under the Amazon verified account so that customers can avoid throttling from Docker Hub

- [ ] [Add the relevant documentation](https://github.com/opensearch-project/documentation-website/issues/631)
- [x] Add support to push to ECR in JenkinsFile
- [x] Copy existing released images from dockerhub staging to ecr staging
- [x] Copy existing released images from dockerhub prod to ecr prod
- [x] https://github.com/opensearch-project/opensearch-build/issues/1518
- [x] https://github.com/opensearch-project/opensearch-ci/issues/65
- [x] #1706
- [x] Make sure ECR images are published from a verified account

**Acceptance Criteria**
- [x] Docker build job should push the docker image on ECR
- [x] Jenkins job to promote the image from staging to production
- [x] ECR repository and roles are deployed using cdk
- [x] Copy existing released images from dockerhub staging to ecr staging
- [x] Copy existing released images from dockerhub prod to ecr prod
- [ ] The ci builds uses the new jenkins job to build docker images

**Comment by abhinavGupta16** [comment]
Update - 
Things tried so far - 
- Tried using existing policy and role to upload from opensearch-ci deployment of jenkins. Facing issues with docker installation
- Created jenkins job on dev-jenkins, added role permissions to the jenkins agent node and main node, faced issues of aws versions
- Updated docker image with awscli v1.22 to be able to run aws cli commands for ECR
- Faced issues using credentials with using docker inside a docker container on jenkins, attempting to run the docker login on agent node first.
- updating the agent node to have awscli 2 to be able to run ECR commands

**Comment by peterzhuamazon** [comment]
After testing ECR indeed support multi-arch image.
It is just not as clear as docker hub shows in different architecture.
In fact, it only shows untagged images because they are layers of different arch.
![Screen Shot 2021-12-09 at 4 25 41 PM](https://user-images.githubusercontent.com/65193828/145478152-4c0445b1-70e5-46ca-96fd-f884256c5ac3.png)

```

$ docker buildx build --platform linux/amd64,linux/arm64 -t public.ecr.aws/a5n0l3m1/opensearch-test:alpinelatest-test -f ./alpine.dockerfile --push .
[+] Building 12.7s (13/13) FINISHED
 => [internal] load build definition from alpine.dockerfile                                                                                                                                                                                             0.0s
 => => transferring dockerfile: 88B                                                                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                                                                                         0.0s
 => [linux/arm64 internal] load metadata for docker.io/library/alpine:latest                                                                                                                                                                            2.7s
 => [linux/amd64 internal] load metadata for docker.io/library/alpine:latest                                                                                                                                                                            2.6s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                                                                                                                           0.0s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                                                                                                                           0.0s
 => [linux/arm64 1/2] FROM docker.io/library/alpine:latest@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300                                                                                                                      1.4s
 => => resolve docker.io/library/alpine:latest@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300                                                                                                                                  0.0s
 => => sha256:9b3977197b4f2147bdd31e1271f811319dcd5c2fc595f14e81f5351ab6275b99 2.72MB / 2.72MB                                                                                                                                                          1.3s
 => => extracting sha256:9b3977197b4f2147bdd31e1271f811319dcd5c2fc595f14e81f5351ab6275b99                                                                                                                                                               0.1s
 => [linux/amd64 1/2] FROM docker.io/library/alpine:latest@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300                                                                                                                      2.0s
 => => resolve docker.io/library/alpine:latest@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300                                                                                                                                  0.0s
 => => sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 2.82MB / 2.82MB                                                                                                                                                          1.9s
 => => extracting sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3                                                                                                                                                               0.1s
 => [linux/arm64 2/2] RUN echo 123 > /tmp/123                                                                                                                                                                                                           0.2s
 => [linux/amd64 2/2] RUN echo 123 > /tmp/123                                                                                                                                                                                                           0.1s
 => exporting to image                                                                                                                                                                                                                                  7.7s
 => => exporting layers                                                                                                                                                                                                                                 0.1s
 => => exporting manifest sha256:8420ea02045e96f7b5483e44962e579e9d6c868675b59a9e907045bf319d0ca8                                                                                                                                                       0.0s
 => => exporting config sha256:3edecbe75e50d664967dccec70cc5bed29928f1234bc7023560a7ab136261ea3                                                                                                                                                         0.0s
 => => exporting manifest sha256:7a18d63dfb5f2ebb8ec73caf427abb9da343bc91539c3148871e0c6fef08d651                                                                                                                                                       0.0s
 => => exporting config sha256:f56dd8613adbd322df5ed952f24634a1bb91039e0499a6de0b4339bda152ca9b                                                                                                                                                         0.0s
 => => exporting manifest list sha256:850743de95ea36b65e1bfbd7f025fd57f8965a40647b641d2a290826547a5006                                                                                                                                                  0.0s
 => => pushing layers                                                                                                                                                                                                                                   6.7s
 => => pushing manifest for public.ecr.aws/a5n0l3m1/opensearch-test:alpinelatest-test@sha256:850743de95ea36b65e1bfbd7f025fd57f8965a40647b641d2a290826547a5006                                                                                           0.9s
 => [auth] aws:: a5n0l3m1/opensearch-test:pull,push token for public.ecr.aws                                                                                                                                                                            0.0s
 => [auth] aws:: a5n0l3m1/opensearch-test:pull,push token for public.ecr.aws
```

```

FROM alpine:latest
RUN echo 123 > /tmp/123
```

x64:
```
public.ecr.aws/a5n0l3m1/opensearch-test   alpinelatest-test                                              3edecbe75e50   2 minutes ago   5.59MB
```

arm64:
```
public.ecr.aws/a5n0l3m1/opensearch-test                        alpinelatest-test   sha256:850743de95ea36b65e1bfbd7f025fd57f8965a40647b641d2a290826547a5006   f56dd8613adb   4 minutes ago   5.33MB
```

```

[ec2-user@ip-172-31-24-166 ~]$ docker exec -it 76aaf4c2543f5a238f20faefb883d7d80d9d14754554f502d349639179d26656 /bin/sh
/ # cat /etc/*release
3.15.0
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.0
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
/ # cat /etc/*release^C
/ # uname -a
Linux 76aaf4c2543f 4.14.252-195.483.amzn2.aarch64 #1 SMP Mon Nov 1 20:59:00 UTC 2021 aarch64 Linux
```

**Comment by abhinavGupta16** [comment]
I am able to build and push the multiarch image on ECR with 2 images showing as untagged and one image with the required tagged.

**Comment by abhinavGupta16** [comment]
Issue on hold since 12/15/21 as working on priority release

**Comment by abhinavGupta16** [comment]
Reopening the issue with added items to the acceptance criteria

**Comment by prudhvigodithi** [comment]
Dockerhub and ECR registries for opensearchproject are in sync
https://gallery.ecr.aws/opensearchproject?page=1
https://hub.docker.com/u/opensearchproject
