### ISSUE TITLE
[Meta] OpenSearch / OpenSearch Dashboards - Windows distribution (X64)

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/opensearch-build#33]
**Describe the solution you'd like**
Provide signed (X64)Windows artifact for OpenSearch / OpenSearch Dashboards

**Additional context**
Currently there are no Windows artifacts for OpenSearch / OpenSearch Dashboards

**Current State (2021/10/28)**

You can build on Windows or build cross-platform for Windows on Linux or MacOS.

1. Install pre-requisites (everything needed in [OpenSearch Dev Guide](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md) + maven for Security Plugin).
2. Build artifacts from source, `./build.sh manifests/1.1.0/opensearch-1.1.0.yml --platform windows`
3. Assemble a bundle, `./assemble.sh buids/manifest.yml`.
4. Produces `opensearch-1.1.0-SNAPSHOT-windows-x64.zip`.
5. Extract .zip, e.g. into `C:\Program Files\OpenSearch`
6. Run `bash plugins/opensearch-security/tools/install_demo_configuration.sh` and follow prompts to create demo certificate.
7. `mkdir logs` (https://github.com/opensearch-project/OpenSearch/issues/1463)
8. Run `bin\opensearch.bat`, server will start.
9. `curl https://localhost:9200 -u admin:admin --insecure`

<details>
<summary>
(Old Tasks)
</summary>

**Remaining**
- [ ] Add Windows CI into OpenSearch and every component, passing tests
   - [ ] https://github.com/opensearch-project/OpenSearch/issues/1448
   - [ ] https://github.com/opensearch-project/OpenSearch/issues/1463
   - [ ] https://github.com/opensearch-project/security/issues/1476
   - [ ] https://github.com/opensearch-project/common-utils/issues/86
   - [ ] https://github.com/opensearch-project/opensearch-plugins/issues/95
   - [ ] https://github.com/opensearch-project/k-NN/issues/152
   - [ ] https://github.com/opensearch-project/sql/issues/247
   - [ ] https://github.com/opensearch-project/common-utils/issues/85
   - [ ] https://github.com/opensearch-project/performance-analyzer/issues/74
   - [ ] https://github.com/opensearch-project/opensearch-build/issues/828
   - [ ] https://github.com/opensearch-project/opensearch-build/issues/826
          https://github.com/opensearch-project/opensearch-build/issues/827
- [ ] Create a Windows docker image to build on Windows
- [ ] Add Windows build to Jenkins 
- [x] https://github.com/opensearch-project/opensearch-build/issues/1430

**Done**

- [x] https://github.com/opensearch-project/OpenSearch/issues/1379
        https://github.com/opensearch-project/OpenSearch/pull/1412
        https://github.com/opensearch-project/opensearch-build/pull/767
        https://github.com/opensearch-project/opensearch-build/pull/768
        https://github.com/opensearch-project/opensearch-build/pull/772
- [x] https://github.com/opensearch-project/opensearch-build/pull/803
- [x] https://github.com/opensearch-project/opensearch-build/pull/804
       https://github.com/opensearch-project/opensearch-build/pull/807
- [ ] https://github.com/opensearch-project/opensearch-build/pull/809

</details>

**Design Document**
* https://github.com/opensearch-project/opensearch-build/issues/2312

**OpenSearch and OpenSearch Dashboards**
* https://github.com/opensearch-project/OpenSearch/issues/1448
* https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2451

**Plugins Meta Issues**
* https://github.com/opensearch-project/opensearch-plugins/issues/95

**Milestones**
* https://github.com/opensearch-project/opensearch-build/issues/2306
* https://github.com/opensearch-project/opensearch-build/issues/2307
* https://github.com/opensearch-project/opensearch-build/issues/2308
* https://github.com/opensearch-project/opensearch-build/issues/2309
* https://github.com/opensearch-project/opensearch-build/issues/2310
* https://github.com/opensearch-project/opensearch-build/issues/2311

**MSI Only Issue**:
* https://github.com/opensearch-project/opensearch-build/issues/2929

**Comment by cashel1** [comment]
The greatest value and the least effort would be a ZIP deliverable.   This would be sufficient for windows desktop developers and sysadmins installing on a server.  Thanks

**Comment by spaceghostcowboy** [comment]
Hello, we would also be interested in an installable Windows version or instructions on how to get this working on Windows. We were about to implement this tech into a project and then saw the lic change and fork. We are eager to get onto the forked version and get something into prod. Thank you for reading this.

**Comment by dblock** [comment]
If anyone on this issue wants to contribute I'd start with #332. The python build workflow will need a bit of work to execute properly on Windows, it currently assumes a lot of *nix paths.

**Comment by cjcjameson** [comment]
We are looking at https://discuss.opendistrocommunity.dev/t/windows-installation/6555/6 which talks about workarounds, but also hoping to get this supported natively with a distribution released.

Sad that it moved to target 1.3 (https://github.com/orgs/opensearch-project/projects/1?card_filter_query=windows) but looking for ways to help.

**Comment by marianotn** [comment]
+1 too

**Comment by dblock** [comment]
To work this POC into our build process. Looking at https://github.com/opensearch-project/opensearch-build/pull/733/files I think we need to make a few changes to produce a Windows zip during the assemble step.

> The Windows release are based on the LINUX tarball. Here are the steps to produce a OpenSearch Windows Zip.

Should be based on the output of `build.sh`, so create another manifest (e.g. opensearch-windows-1.1.0.yml) that doesn't have the components that are currently not supported on Windows. In the future we can consider improving and adding a list of platforms to each component to merge these manifests. 

1. Download the latest tarball from opensearch.org [downloads page](https://opensearch.org/downloads.html).

Calling `build.sh manifests/1.1.0/opensearch-windows-1.1.0.yml` will produce the set of components today with no code changes. 

If we want to use released artifacts, then we can use the manifest that was produced with the released build and remove the components from it, manually is fine. 

2. Untar the tarball.

Either building from source or using a released manifest replaces this.

3. Download the latest release of Windows JDK14 from AdoptOpenJDK [here](https://adoptopenjdk.net/installation.html?variant=openjdk14&jvmVariant=hotspot#x64_win-jdk)

Short term: [The code that extracts the min tarball](https://github.com/opensearch-project/opensearch-build/blob/main/src/assemble_workflow/bundle.py#L73) needs to also run a custom post-install script that will delete the JDK and install a Windows JDK. We already have custom install scripts [run for each plugin](https://github.com/opensearch-project/opensearch-build/blob/bca209e0b481af5a8afbb9d2d41f5bb7e6350b6c/src/assemble_workflow/bundle.py#L52), we need to carry that over to the min bundle.

Long term: we'll want to support building a `-min` no-JDK bundle on Linux targeting Windows and include that in the manifest. 

4. Extract the archive, rename the folder to `jdk` and replace it with the bundled `jdk` folder from the OpenSearch LINUX tarball.

See above.

5. Go into the bin folder, and run `./opensearch-plugin remove <Plugin Folder Name>` to remove `opensearch-knn` and `opensearch-performance-analyzer`.

See (1), won't be necessary.

6. Remove knn and performance analyzer related configurations from `opensearch-tar-install.sh`, but it is optional, as it will not stop OpenSearch from launching on Windows.

See (1), won't be necessary.

7. You can start OpenSearch on Windows either by running `opensearch-tar-install.sh` or by running `bin/opensearch` from Shell.
8. If you want to start OpenSearch by running .bat files, you need to make some tweaks based on the OpenDistro for Elasticsearch Windows Zip [here](https://opendistro.github.io/for-elasticsearch/downloads.html#develop).
   You can unzip the archive, copy all the .bat files from ODFE bin folder to OpenSearch bin folder. Make corresponding tweaks, and make them run for OpenSearch.
 
Can bring any .bat files along the way in (3).

**Comment by dblock** [comment]
@peternied Do we have a permalink to the public location for the released 1.1.0 build manifest.yml?

**Comment by AndreVirtimo** [comment]
I have seen this issue isn't in the roadmap board anymore. Is it not planed to provide a distro for Windows?

**Comment by bbarani** [comment]
We are currently focussed on creating Linux based distributions at this point in time. Please feel free to provide your inputs on this issue https://github.com/opensearch-project/opensearch-build/issues/741 to finalize the priority order for non Linux distributions. As always, we welcome any contribution towards the  development of new distributions.

**Comment by dblock** [comment]
Related, https://github.com/opensearch-project/logstash-output-opensearch/issues/119

**Comment by ZakMcKrack3n** [comment]
Elastic search refactoring seems to altered the commands within service scripts from //ES to //OPENSEARCH:

https://github.com/opensearch-project/OpenSearch/blob/3e9a420533f67157ea521fe23212a3a07754c2bf/distribution/src/bin/opensearch-service.bat#L48
https://github.com/opensearch-project/OpenSearch/blob/3e9a420533f67157ea521fe23212a3a07754c2bf/distribution/src/bin/opensearch-service.bat#L69

Where //ES stands for 


//ES | Edit service configuration | This is the default operation.
-- | -- | --

From Apaches procrun I presume, not elastic search.
Possibly more scripts affected, just came up when wanting to test as a service within windows.

**Comment by bhupendra-mskhatri** [comment]
Hi, any update for the distro for windows.

**Comment by dblock** [comment]
> Hi, any update for the distro for windows.

I am afraid it's still in the same state as [what I said above](https://github.com/opensearch-project/opensearch-build/issues/33#issuecomment-954220510). Please pickup any of the above open items if you have some hands.

**Comment by bhupendra-mskhatri** [comment]
Thankyou @dblock . I understand the delay because of the shortage of hands, but would you have a high level time limit so that we can plan accordingly for our clients.

**Comment by mridulchadha84** [comment]
> Thankyou @dblock . I understand the delay because of the shortage of hands, but would you have a high level time limit so that we can plan accordingly for our clients.

+1

**Comment by yosiasz** [comment]
great work! but I I will stick with es for now.

**Comment by burck1** [comment]
> Elastic search refactoring seems to have altered the commands within service scripts from //ES to //OPENSEARCH:
> 
> https://github.com/opensearch-project/OpenSearch/blob/3e9a420533f67157ea521fe23212a3a07754c2bf/distribution/src/bin/opensearch-service.bat#L48 https://github.com/opensearch-project/OpenSearch/blob/3e9a420533f67157ea521fe23212a3a07754c2bf/distribution/src/bin/opensearch-service.bat#L69
> 
> Where //ES stands for
> 
> //ES	Start (execute) the service
> From Apaches 'Procrun service application' I presume, not elastic search. Possibly more scripts affected, just came up when wanting to test as a service within windows.

@ZakMcKrack3n, FYI, ran into this today, [PR](https://github.com/opensearch-project/OpenSearch/pull/4289) submitted.

**Comment by peterzhuamazon** [comment]
Hi All,

We are able to add Windows Snapshot distribution build into our Jenkins Pipeline.
Here are the links for you to access `OpenSearch Min (without plugins) in Windows x64 Zip` format:

1.3.5: https://artifacts.opensearch.org/snapshots/core/opensearch/1.3.5-SNAPSHOT/opensearch-min-1.3.5-SNAPSHOT-windows-x64-latest.zip
2.2.1: https://artifacts.opensearch.org/snapshots/core/opensearch/2.2.1-SNAPSHOT/opensearch-min-2.2.1-SNAPSHOT-windows-x64-latest.zip
2.3.0: https://artifacts.opensearch.org/snapshots/core/opensearch/2.3.0-SNAPSHOT/opensearch-min-2.3.0-SNAPSHOT-windows-x64-latest.zip
3.0.0: https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-windows-x64-latest.zip


Note that all of these zips are SNAPSHOT, non-production-ready artifacts, which is only available for testing purposes.

We welcome your feedbacks and suggestions as these artifacts will be updated overtime.

Thanks.

**Comment by dblock** [comment]
It looks like we're making progress on the Windows distribution, but I am a bit concerned that we're not adding Windows CI to OpenSearch core itself, which is https://github.com/opensearch-project/OpenSearch/issues/1448. cc: @CEHENKLE

**Comment by CEHENKLE** [comment]
> It looks like we're making progress on the Windows distribution, but I am a bit concerned that we're not adding Windows CI to OpenSearch core itself, which is [opensearch-project/OpenSearch#1448](https://github.com/opensearch-project/OpenSearch/issues/1448). cc: @CEHENKLE

What date would we need this by? (@minalsha)

**Comment by dblock** [comment]
> > It looks like we're making progress on the Windows distribution, but I am a bit concerned that we're not adding Windows CI to OpenSearch core itself, which is [opensearch-project/OpenSearch#1448](https://github.com/opensearch-project/OpenSearch/issues/1448). cc: @CEHENKLE
> 
> @bbarani / @peterzhuamazon -- What date would we need this by? (flagging for @minalsha)

I think this is a must have if we're going to be making any official distribution for Windows. We have to ensure that tests pass.

**Comment by peterzhuamazon** [comment]
I am a bit confused if you are talking about windows snapshot in build repo, it is currently commented out because of some bugs I am fixing, but it is able to run tho.

if you are talking about core repo then I am not doing anything there.

Thanks.

**Comment by dblock** [comment]
@peterzhuamazon This is exactly what I am raising - the distribution build for windows is working, but we aren't running tests on windows in OpenSearch core.

**Comment by peterzhuamazon** [comment]
Windows Issues Board:
* common-utils: https://github.com/opensearch-project/common-utils/issues/238
* alerting: https://github.com/opensearch-project/alerting/issues/557
* security: https://github.com/opensearch-project/security/issues/2122

**Comment by rursprung** [comment]
how do you run the jenkins builds on windows? this line here:
https://github.com/opensearch-project/opensearch-build/blob/55b26223f5b6047f934f604a241f01f2328d8eb8/scripts/components/OpenSearch/build.sh#L87

doesn't return `windows` for me when running it in mingw64 (part of Git for Windows):
```
$ uname -s
MINGW64_NT-10.0-19042
```

though it's _probably_ not an issue as you're explicitly already passing it in here:
https://github.com/opensearch-project/opensearch-build/blob/55b26223f5b6047f934f604a241f01f2328d8eb8/jenkins/opensearch/distribution-build.jenkinsfile#L220

nevetheless, it might be worth it to explicitly handle windows in `build.sh` so that the script can be also be run manually w/o having to explicitly set the platform on windows?

**Comment by dblock** [comment]
That build.sh is called from the [build workflow](https://github.com/opensearch-project/opensearch-build/blob/main/src/build_workflow/README.md) which supports `--platform`.

**Comment by anirudha** [comment]
do we have a Dashboards artifact for windows to test ?

**Comment by peternied** [comment]
@bbarani @CEHENKLE @davidlago We've got an parity support question for this upcoming release.

In the Security Plugin there is support for using OpenSSL instead of the Java's native SSLEngine, this features defaults to off and is only supported when running JDK11.  It works with no issues on Linux and MacOS platforms running JDK11.

Windows is non-trivially different and we have yet to get the feature working on this platform (~2 dev days of effort).  Based on its complexity, and redundancy; I am of the opinion that we should not consider this a release blocker windows platform.  We instead will update the feature to be disabled on Windows and update the documentation accordingly.  Post 2.4.0 if there is interest, support for OpenSSL could be added.

Alternatively, if we focus on supporting OpenSSL for windows on JDK 11 I have low confidence we will deliver this feature for the feature freeze date of 11/03, we can have a better completion estimate for the EOD of Monday 11/01.

What do you think of dropping OpenSSL support for the Windows platform in 2.4.0?

[1] https://github.com/opensearch-project/security/issues/2195

**Comment by davidlago** [comment]
My $0.02 is to not block 2.4 on Windows for this support, as it is something that is not universally supported (across JDK versions) for our other distributions and there is an alternative SSL engine. Also, we never had a Windows release, supporting OpenSSL to begin with, so this is not technically "dropping" support potentially breaking some folks who were already relying on it.

**Comment by peternied** [comment]
> What do you think of dropping OpenSSL support for the Windows platform in 2.4.0?

Circling back, turns out OpenSSL does not work on linux platforms either and hasn't for an indeterminate amount of time, this is not a platform specific issue anymore and so should have no impact on the 2.4.0 release.  Thanks!

**Comment by peterzhuamazon** [comment]
We have windows release candidate prepared for release on 2.4.0:
https://github.com/opensearch-project/opensearch-build/issues/2649#issuecomment-1304654620

Thanks.

**Comment by peterzhuamazon** [comment]
Official Windows 2.4.0 ZIP is released now:
* https://opensearch.org/downloads.html

Thanks.

**Comment by bbarani** [comment]
@peterzhuamazon Please close this issue and create separate issues for pending action items.

**Comment by peterzhuamazon** [comment]
Our 1.3.7 Version start supporting Windows ZIP for 1.x line:
* https://opensearch.org/versions/opensearch-1-3-7.html

**Comment by bbarani** [comment]
Closing this issue as we have added Windows support to both 1.x and 2.x versions.
