### ISSUE TITLE
[Meta] Improve OpenSearch packaging

### ISSUE THREAD

**Issue by smortex** [opensearch-project/opensearch-build#4087]
### Describe the bug

OpenSearch / OpenSearch Dashboard packages can be improved in several areas. Some of these improvements can arguably be considered breaking changes because they may somewhat disrupt users workflow.  This PR is intended to aggregate the packaging improvement progress, see where we are and what are the next moves.

* [x] Announce future changes https://github.com/opensearch-project/opensearch-build/pull/4051
* [ ] Package install files with insecure permissions https://github.com/opensearch-project/opensearch-build/issues/4084
  * [ ] https://github.com/opensearch-project/opensearch-build/pull/4043
* [ ] Package does not restart service on update https://github.com/opensearch-project/opensearch-build/issues/3891
* [ ] Package overwrite configuration files on update https://github.com/opensearch-project/opensearch-build/issues/4084

### To reproduce

n/a

**Comment by automaticserver** [comment]
The postinst Script inside opensearch package has several problems. First it doesn't use the right abstraction tools. Never use "systemctl" or "service" or whatever directly to interact with the init system. For good reasons there are abstractions to handle implementation details of the currrent init system.

Please use:
- invoke-rc.d to start/stop/restart service
- update-rc.d to enable/disable a service

https://www.debian.org/doc/debian-policy/ch-opersys.html#running-init-scripts

They does always the RIGHT thing, even if a system administrator changes his init system. You can rely on them and save code inside postinst.

**Comment by peterzhuamazon** [comment]
> The postinst Script inside opensearch package has several problems. First it doesn't use the right abstraction tools. Never use "systemctl" or "service" or whatever directly to interact with the init system. For good reasons there are abstractions to handle implementation details of the currrent init system.
> 
> Please use:
> 
>     * invoke-rc.d to start/stop/restart service
> 
>     * update-rc.d to enable/disable a service
> 
> 
> https://www.debian.org/doc/debian-policy/ch-opersys.html#running-init-scripts
> 
> They does always the RIGHT thing, even if a system administrator changes his init system. You can rely on them and save code inside postinst.

That is a good callout @automaticserver we will look into those abstractions.
Thanks.

**Comment by automaticserver** [comment]
Please have a look at my newly created proposal: #4243. E.g. there would be no need to implicitly use the abstractions as debhelper would generate those parts in the maintainer script the correct way automatically.

/dm

**Comment by peterzhuamazon** [comment]
We will close the bugs related to 2.x, and will move some issues to track in the next possible major version.

**Comment by peterzhuamazon** [comment]
A new meta issue for the next major version release will be created later.

**Comment by peterzhuamazon** [comment]
Closing for now.
