### ISSUE TITLE
[META] Ensure 2.11 branch readiness for 2.11.1 release

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#4199]
Coming from https://github.com/opensearch-project/opensearch-build/issues/4161 this issue tracks all child issues for ensuring branch readiness for 2.11.1 release. 

## What is happening?
We are planning `2.11.1` release in upcoming few weeks. Following the semver guildelines and branching strategy, this release will be based on `2.11` as a reference branch

## Why?
1. We need this release because of a critical breaking bug in the [security plug-in](https://github.com/opensearch-project/OpenSearch/issues/10802). This bug impacts everyone using logstash and the only work around is to turn off compression (which is expensive) 

1.  As a refresher, our normal process is to commit changes to main, then backport to 2.x. Since the 1.0 release, we only backport bug fixes and security changes to the current 2.x branch (in this case 2.11) so that if we need to we can quickly do a patch release. 

1. There are two reason we don’t back port features to the current release branch (right now 2.11):
    1. Because we want patch release to be as thin as possible, and the more changes you make, the more verification we need to do
    1. Adding features in a patch breaks semver.

However, looking at the list of changes for 2.11, we currently have a mix of [features that have been merged in](https://github.com/opensearch-project/opensearch-build/issues/4161#issuecomment-1788089723). After providing several options and discussing with all the component teams as well as community we came to the [conclusion](https://github.com/opensearch-project/opensearch-build/issues/4161#issuecomment-1793259396) of reverting all feature related changes from 2.11 branch.

- [x] opensearch-project/alerting#1297
- [x] opensearch-project/anomaly-detection#1097
- [x] opensearch-project/asynchronous-search#509
- [x] opensearch-project/common-utils#559
- [x] opensearch-project/reporting#926
- [x] opensearch-project/index-management#1032
- [x] opensearch-project/job-scheduler#538
- [x] opensearch-project/k-NN#1294
- [x] opensearch-project/performance-analyzer#592
- [x] opensearch-project/performance-analyzer-rca#516
- [x] opensearch-project/security#3650
- [x] opensearch-project/sql#2417
- [x] opensearch-project/observability#1765
- [x] opensearch-project/cross-cluster-replication#1283
- [x] opensearch-project/ml-commons#1592
- [x] opensearch-project/geospatial#582
- [x] opensearch-project/notifications#812
- [x] opensearch-project/neural-search#486
- [x] opensearch-project/security-analytics#714
- [x] opensearch-project/custom-codecs#80
- [x] opensearch-project/dashboards-query-workbench#210
- [x] opensearch-project/alerting-dashboards-plugin#792
- [x] opensearch-project/notifications#813
- [x] opensearch-project/security-dashboards-plugin#1643
- [x] opensearch-project/index-management-dashboards-plugin#914
- [x] opensearch-project/anomaly-detection-dashboards-plugin#646
- [x] opensearch-project/reporting#927
- [x] https://github.com/opensearch-project/dashboards-reporting/issues/253
- [x] opensearch-project/dashboards-observability#1230
- [x] opensearch-project/dashboards-visualizations#289
- [x] opensearch-project/dashboards-search-relevance#348
- [x] opensearch-project/dashboards-maps#559
- [x] opensearch-project/security-analytics-dashboards-plugin#779
- [x] opensearch-project/ml-commons-dashboards#283
- [x] opensearch-project/OpenSearch#11094
- [x] opensearch-project/OpenSearch-Dashboards#5431

**Comment by Swiddis** [comment]
Looks like [observability](https://github.com/opensearch-project/observability/issues) got two issues (1765 and 1766), I assume one of those is meant for [dashboards-observability](https://github.com/opensearch-project/dashboards-observability/issues)

**Comment by gaiksaya** [comment]
> Looks like [observability](https://github.com/opensearch-project/observability/issues) got two issues (1765 and 1766), I assume one of those is meant for [dashboards-observability](https://github.com/opensearch-project/dashboards-observability/issues)

Looks like it. I used the meta tool [here](https://github.com/opensearch-project/opensearch-plugins/blob/main/META.md) to create issues. Maybe check if there is some issue with re-direct of GitHub repo naming there? I'll move one of the issue to dashboards-observability.
Thanks!

**Comment by mengweieric** [comment]
Sql also has duplicated issues 2147 and 2148, plus we are missing [query workbench](https://github.com/opensearch-project/dashboards-query-workbench) and [dashboard reports](https://github.com/opensearch-project/dashboards-reporting).

**Comment by gaiksaya** [comment]
> Sql also has duplicated issues 2147 and 2148, plus we are missing [query workbench](https://github.com/opensearch-project/dashboards-query-workbench) and [dashboard reports](https://github.com/opensearch-project/dashboards-reporting).

You can move the issues from sql to those repos. Taking care of it of it for now.

**Comment by gaiksaya** [comment]
Closing this issue as all related action item sub-issues are now addressed.
Thanks!
