### ISSUE TITLE
[Meta] OpenSearch 1.1.0 Release Validation

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#474]
# Build Details
OpenSearch 1.1.0 build is _not yet available_.  When the build has been created, it will be documented here.

# Release Validation Status
Below are all the components that need validation, @peternied  will add links to issues as they are available.

- [ ] OpenSearch Core
  - [ ] Integration tests pass
  - [ ] Performance tests
  - [ ] Backwards compatibility tests
- [ ] OpenSearch
  - [ ] Integration tests pass
- [ ] common-utils
  - [ ] Integration tests pass
- [ ] job-scheduler
  - [ ] Integration tests pass
- [ ] sql
  - [ ] Integration tests pass
- [ ] alerting
  - [ ] Integration tests pass
- [ ] security
  - [ ] Integration tests pass
- [ ] performance-analyzer-rca
  - [ ] Integration tests pass
- [ ] performance-analyzer
  - [ ] Integration tests pass
- [ ] index-management
  - [ ] Integration tests pass
- [ ] k-NN
  - [ ] Integration tests pass
- [ ] anomaly-detection
  - [ ] Integration tests pass
- [ ] asynchronous-search
  - [ ] Integration tests pass
- [ ] dashboards-reports
  - [ ] Integration tests pass
- [ ] dashboards-notebooks
  - [ ] Integration tests pass
