### ISSUE TITLE
[META] Automate performance benchmark for OpenSearch and components

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#4906]
This meta issue is to track all the completed and upcoming features related to automating performance benchmarks on OpenSearch. 

### Features
- [x] Automate nightly benchmarks for OpenSearch mainline, 2x and 1x line. https://github.com/opensearch-project/opensearch-benchmark/issues/102. #3100 
- [x] Support running benchmarks against user's cluster endpoint. #4478 
- [x] Support running performance benchmarks on OpenSearch pull requests. https://github.com/opensearch-project/OpenSearch/issues/14553
- [x] Add feature to also publish baseline comparison results on pull request runs. https://github.com/opensearch-project/OpenSearch/issues/14826
- ~[ ] Control plane for submitting ad-hoc benchmark runs. #4231 #4788~
- [x] Alerting and monitoring on benchmark metrics. #3647
