### ISSUE TITLE
[META] Add input validation checks and debug logs for test jobs

### ISSUE THREAD

**Issue by setiah** [opensearch-project/opensearch-build#522]
To improve debug-ability and prevent common mistakes, we should add some input validation checks and debug logs in the test script.

- [x] Add input parameter validation that checks the provided opensearch version, architecture and build id are in the right format: https://github.com/opensearch-project/opensearch-build/pull/539
- [x] Log the s3 key for debugging s3 download failures. 
- [x] Add logs for plugin tests on jenkins?
- [x] #525

**Comment by minalsha** [comment]
@setiah what do you mean by "Add logs for plugin tests on jenkins?"  Is this if we dont have test recorder and test publisher done and hence we would need the logs for Plugins tests on Jenkins?

**Comment by setiah** [comment]
Yeah the test recorder should publish all the logs to s3 eventually. In the mean time, we need some messaging on jenkins dashboard itself for an integration test run on a component to know if it failed or succeeded. #549 adds log messages if the component test failed.
