### ISSUE TITLE
[Meta] OpenSearch Dashboard Build / Release Process

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#573]
With the OpenSearch service distribution being built and validated, our desire is to adopt the same process with the OpenSearch Dashboard.

* [ ] Create Dashboard Manifest
  * https://github.com/opensearch-project/opensearch-build/issues/158
* [ ] Automation build process
  * https://github.com/opensearch-project/opensearch-build/issues/158
* [ ] Bundle all build artifacts into a releasable distribution
* [ ] Validate the distribution
* [ ] Automate new Dashboards versions
* [ ] Automate release guidelines for Dashboards and components
* [ ] Documentation for release process
* [ ] Documentation for onboarding

Tenets:
* Always be committing, pull request small(est) functional functions
* High quality delivery, add more ci workflows and unit tests
* Clean roadmap, create issues on everything to to help encourage contributions
* Reproducible, minimize the number of dependencies and data that needs to be passed around the system.

**Comment by kavilla** [comment]
Can't check off.

Build: https://github.com/opensearch-project/opensearch-build/pull/590
Cleanup: https://github.com/opensearch-project/opensearch-build/pull/601

**Comment by tianleh** [comment]
https://github.com/opensearch-project/opensearch-build/issues/604

**Comment by dblock** [comment]
I checked off the first two boxes, but we still need all the other components to come in and add themselves to check the rest.

**Comment by peternied** [comment]
> Can't check off.

Fixed, @opensearch-project/opensearch-test has access to edit/update issues

**Comment by tmarkley** [comment]
@peternied very minor, but can we be consistent with the `OpenSearch Dashboards` name?

**Comment by peternied** [comment]
@kavilla Is this meta issue up to date?

**Comment by peternied** [comment]
@tianleh @kavilla We have an over arching automation tracking issue, https://github.com/opensearch-project/opensearch-build/issues/1361 please let me know if there are other items that you think should be promoted into that tracking issue or this one.

**Comment by peternied** [comment]
@seanneumann @kavilla How is this meta issue trending, is it still useful?

**Comment by bbarani** [comment]
@seraphjiang @kavilla Can you update this META issue with current status?

**Comment by tianleh** [comment]
For the status of https://github.com/opensearch-project/opensearch-build/issues/604 , we have finished 
1) support running OSD integ test from test.sh
2) onboard all Dashboards plugin teams to the functional test repo
3) run OSD integ test from Jenkins bundle build job

There is a few stability issue when running the Cypress tests from the Jenkins job. We are working with infra team to address these. See the "Fast Followups" section of https://github.com/opensearch-project/opensearch-build/issues/604

**Comment by bbarani** [comment]
@seraphjiang @kavilla Can you update this issue with current status?
