### ISSUE TITLE
[META] Setup Jenkins using CDK

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-build#581]
### Is your feature request related to a problem? Please describe

We need to setup Jenkins automatically using CDK

### Describe the solution you'd like

CDK should be able to deploy a production ready jenkins

### Action Items
- [x] https://github.com/opensearch-project/opensearch-build/issues/580
- [x] https://github.com/opensearch-project/opensearch-ci/issues/6
- [ ] https://github.com/opensearch-project/opensearch-ci/issues/23
- [ ] https://github.com/opensearch-project/opensearch-ci/issues/24
- [ ] https://github.com/opensearch-project/opensearch-ci/issues/25
