### ISSUE TITLE
[Meta] Update Branch Protection Rules - Disable dismissing stale review

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#691]
Today we have the following branch protection rules in place for `main`:

- [x] Require a pull request before merging
  + [x] Require approvals: **2**
  + [x] Dismiss stale pull request approvals when new commits are pushed
  + [ ] Require review from Code Owners
  + [ ] Restrict who can dismiss pull request reviews
- [x] Require status checks to pass before merging
  + [x] Require branches to be up to date before merging
- [ ] Require conversation resolution before merging
- [ ] Require signed commits
- [x] Require linear history
- [ ] Include administrators
- [ ] Restrict who can push to matching branches

I propose we make the following changes:
- [x] *Unchanged* Require a pull request before merging
  + [ ] *No longer required* Dismiss stale pull request approvals when new commits are pushed
    - Unless intentionally dismissed, approval/request changes entrusts the author of the PR to rebase/fix checks as needed to merge a PR to reduce the number of back/forth conversations.

Lets vote, 👍 👎 on this issue and look to close after we get a 4 votes either wait or Friday the 8th.  If there are other items to address lets duplicate this issue with the specific changes in mind.

If there is a counter proposal lets discuss those in this issue as well.

**Comment by saratvemulapalli** [comment]
Why not "require signed commits?"

**Comment by peternied** [comment]
> Why not "require signed commits?"

@saratvemulapalli Want to start up an new issue you can clone this one?  I've got opinions :)
