### ISSUE TITLE
[META] On-board whitesource native integration

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#721]
### Is your feature request related to a problem? Please describe
We need to scan all public GitHub repositories under OpenSearch organization for security vulnerabilities.

### Describe the solution you'd like
- Use native integration that is available out of the box in Whitesource tool to  schedule / automate the CVE and vulnerability scans on all public GitHub repositories under OpenSearch organization
- [x] #823
- [x] #909
- [x] create github issues if CVEs or vulnerabilities are found.
- [x] #1423
- [x] Do a PR level scan on `opensearch` repository
- [x] extend the PR level scan to other repositories under opensearch org.

### Describe alternatives you've considered
Manually creating CRON jobs to schedule the CVE scans

**Comment by zelinh** [comment]
Reopen this issue since this is META.

**Comment by zelinh** [comment]
Closing this issue since we have onboarded WhiteSource integration on all our repos. Although we are aware that WhiteSource native integration is not working correctly on some of the gradle repos (e.g. core repo, etc..), we have reached out to WhiteSource side and this will be tracked in #1157 .
