### ISSUE TITLE
[Meta] Platform Support

### ISSUE THREAD

**Issue by jcgraybill** [opensearch-project/opensearch-build#741]
### Is your feature request related to a problem? Please describe

There's ongoing work to use OpenSearch and OpenSearch dashboards in environments beyond Linux/x64 and Linux/ARM64, c.f. #33, #38, #101. Most of OpenSearch and its plugins run in the JVM, and most of OpenSearch Dashboards and its plugins run in Node.JS, so packaging the build artifacts from Linux alongside runtimes for Windows, MacOS, FreeBSD, etc will make most OpenSearch features available to those platforms. [WORA](https://en.wikipedia.org/wiki/Write_once,_run_anywhere)!

Making OpenSearch and OpenSearch Dashboards match the Linux experience on these platforms would require some additional work, including:
1. Being incorporated into the Build/CI framework, so that the same integration tests, performance tests, and backwards-compatibility tests are run in these environments.
2. Incorporating native or operating-system-specific components like the native K-NN library, the performance monitor plugin, and the OpenSearch Dashboards Reporting plugin's chromium dependency.
3. Porting/testing all of the shell scripts that ship with OpenSearch as necessary.
4. Creating documentation for administrating this software in the new enviroments, if that differs.
5. Making the process of installing and running OpenSearch idiomatic for that operating system. On Linux, we offer a .tgz and (soon) RPM/DEB packages, but these aren't typically the way FreeBSD, Windows, and Macintosh users install or run software.
6. Confirming that all dependencies are the same between platforms. Node.JS 10, for example, isn't available for all operating systems, so running OpenSearch Dashboards might require using a different version of Node.JS than we currently build and test against. This could lead to unexpected behavior in OpenSearch Dashboards.

The lead time on some of these tasks could be relatively long. Some of them will matter very much to some users, and less to other users. One could imagine a user, for example, who wouldn't want to use OpenSearch with production data on Windows until it's demonstrated to pass its full test suite when running in Windows. Another user might appreciate the convenience of being able to use OpenSearch for development with test data on their MacOS laptop right away. Other users may want to use OpenSearch on their preferred operating system while some of these tasks are still outstanding in order to give feedback on what works and doesn't. 

### Describe the solution you'd like

Let's use this issue to discuss and collect feedback on the questions:
1. Should we produce and make downloadable OpenSearch and OpenSearch Dashboards artifacts for Windows and MacOS (and in the future, other operating systems or architectures) early, while some number of these gaps exist between them and the Linux artifacts?
2. Are there any of the gaps listed above (or others I didn't list) that we would block on?
3. If we do produce OS-specific artifacts that have gaps from the Linux releases, how do we describe this to users? Do we list them separately on the downloads page? Do we label them ("alpha", "beta", "port", "experimental")? Do we caveat or make recommendations about whether they should be used for production workloads?

- [x] https://github.com/opensearch-project/opensearch-build/issues/101
- [x] https://github.com/opensearch-project/opensearch-build/issues/33
- [ ] https://github.com/opensearch-project/opensearch-build/issues/38
- [x] https://github.com/opensearch-project/opensearch-build/issues/27

**Comment by schmitch** [comment]
btw. we are currently using elasticsearch and wanted to make ths witch to opensearch. however not having at least a stable windows distribution means that we can't migrate that easily since we also have lots of windows customers.

we would not mind at all if the windows release does not have the same featureset, as long as it is clearly stated what is different and of course nothing should be broken.

**Comment by TSiege** [comment]
Homebrew support for local development would be amazing. I'm currently working off of docker, but I'm not the most skilled in setting them up and I constantly have issues starting one, successfully connecting etc. Improving local development is crucial for me. I used to be able to dev against an Elasticsearch run in brew, and it was a great experience that never gave me any issues. Having that for Opensearch would be a game changer for me

**Comment by dblock** [comment]
@TSiege There's actually a community contributed Homebrew formulae already, check out https://github.com/opensearch-project/opensearch-build/issues/38#issuecomment-996075677 and https://github.com/Homebrew/homebrew-core/blob/master/Formula/opensearch.rb. I have some concerns given that Homebrew builds from source, but it's a thing.

**Comment by stockholmux** [comment]
@schmitch When you say you have 'lots of windows customers' - are they currently running Elasticsearch production instances on Windows?

**Comment by gruselglatz** [comment]
Maybe i've overlooked something but there is already a deb buildstep [1]. But why is there no download for the deb packages?

Sry if i missed something :) 
[1] https://github.com/opensearch-project/OpenSearch/blob/b78176afefd8c09a19de6bc52907b40c8c4fedf2/distribution/packages/build.gradle#L353

**Comment by AMoo-Miki** [comment]
The FreeBSD port of OpenSearch Dashboards relaxes its NodeJS requirements. Additionally, OSD's helpers have a few guardrails against platforms other than `linux`, `windows`, and `darwin`.
