### ISSUE TITLE
[META] Run integ tests with every build of OpenSearch and OpenSearch Dashboards and publish test results

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#818]
### Is your feature request related to a problem? Please describe

Coming from https://github.com/opensearch-project/opensearch-build/issues/123, the CI workflow produces builds. Next, run integ tests and publish test results.

### Describe the solution you'd like

- [x] #464 
- [x] Determine the correct parameters to run an integration test locally, see https://github.com/opensearch-project/opensearch-build/issues/1333#issuecomment-995241490
- [x] Update the existing [workflow](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/test/testsuite/Jenkinsfile#L53) as a new jenkins workflow off of jenkins/opensearch called integ-test.jenkinsfile that spins up a node of arm/x64 arch and then runs the tests against it
  * Build the test execution logic into the existing `src/var/...groovy` files, jenkins file should be  
- [x] Update the opensearch\distribution.jenkinsfile workflow to trigger the integration tests
  - [x]  After the build is complete the pipeline triggers a test pipeline
  - [x] The test pipeline gets all information needed to spin up test workers
  - [x] The test pipeline triggers notifications on success/failure that are actionable
  - [x] Links to the test publisher results are consumable by receivers of the notification
- [x] https://github.com/opensearch-project/opensearch-build/issues/1274 
- [ ] https://github.com/opensearch-project/OpenSearch/issues/1768
- [x] https://github.com/opensearch-project/opensearch-build/issues/202
- [x] https://github.com/opensearch-project/opensearch-build/issues/704
- [ ] https://github.com/opensearch-project/opensearch-build/issues/58
- [ ] https://github.com/opensearch-project/opensearch-build/issues/1495
- [x] Parallelize integration testing for plugins

**Comment by owaiskazi19** [comment]
Test Publisher is covered as a part of https://github.com/opensearch-project/opensearch-build/issues/341

**Comment by peternied** [comment]
@ohltyler Lets have you start with this issue

**Comment by abhinavGupta16** [comment]
Is this a META issue? It looks like this is holding a lot of issues.

**Comment by gaiksaya** [comment]
@ohltyler Can you check this and other https://github.com/opensearch-project/opensearch-build/issues/124 issue and see if you can combine them into one and close the duplicates?
Thanks!

**Comment by ohltyler** [comment]
@gaiksaya we have been using this one as the latest meta issue for tracking integ test progress. I'm ok to move the remaining P1 tasks in #124 to this repo but don't have permission to edit the issues.

@dblock can you help add the open tasks from there to this issue, and close out #124?

**Comment by ohltyler** [comment]
Can I get permissions to edit issues? I'd like to add #1495 to this list

**Comment by dblock** [comment]
> Can I get permissions to edit issues? I'd like to add #1495 to this list

I added it to the list in the meantime.

**Comment by peternied** [comment]
> Can I get permissions to edit issues? I'd like to add #1495 to this list

Done!

**Comment by gaiksaya** [comment]
Hi @dblock Can you check or update this issue and close if required? We have most of the things. We are running integration tests for all plugins in test manifest as a part of every build now.

**Comment by gaiksaya** [comment]
Closing this issue! We current have each distribution build triggering the integration and BWC test and publishing results.
Thanks!
