### ISSUE TITLE
Publish artifacts into rubygems.org repository

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-build#872]
### Is your feature request related to a problem? Please describe

build and upload gems to rubygems.org repository in following order

https://github.com/opensearch-project/opensearch-ruby/tree/main/opensearch-api
https://github.com/opensearch-project/opensearch-ruby/tree/main/opensearch-transport
https://github.com/opensearch-project/opensearch-ruby/tree/main/opensearch
https://github.com/opensearch-project/opensearch-ruby/tree/main/opensearch-dsl

### Tasks
- [x] Add perms to upload folder on s3
- [x] Update ruby version on docker image used with jenkins
- [x] Create `JenkinsFile` to run the build, sign and upload to s3 pipeline

### Describe the solution you'd like

Should be available at rubygems.org

**Comment by gaiksaya** [comment]
[Triage] We will be following the same process we followed for logstash publishing to rubygems. Need to check if it is possible to automate any steps from that process.
@VijayanB What is the estimated time frame for this release?

**Comment by VijayanB** [comment]
@gaiksaya 11/24

**Comment by gaiksaya** [comment]
Hi @VijayanB Sorry we won't be able to meet the above date. We will get back to you with new estimated date.
Thanks!

**Comment by gaiksaya** [comment]
One solution that I am thinking would work for this is creating a jenkins job to automate build and sign and upload the generated artifacts in S3 bucket.
The only manual process here is to download the generated artifacts from S3, ruby login and publish.

Update: We rebuild the ci [docker image](https://hub.docker.com/layers/opensearchstaging/ci-runner/centos7-x64-arm64-jdkmulti-node10.24.1-cypress6.9.1-20211123/images/sha256-3f0c1cbdcad2ee6aa5709ad4cafce393299a752d440ce5a32288d24adf00b09d?context=explore) required by ruby gems inorder to include the required packages. I am still working on Jenkins workflow. Had a call with @VijayanB  in order to build all the components he is working on build script (PR here: https://github.com/opensearch-project/opensearch-ruby/pull/37) that will help to build all the components. Till the PR is merged and branch is cut for 1.0, I’ll work based on his fork. Once the artifacts are uploaded on S3, the publishing to ruby gems is still a manual process.

Thanks!
