### ISSUE TITLE
Release version 1.2.0 Reset Final sanity testing tracking

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#954]
Confirm that all testing impacted by https://github.com/opensearch-project/opensearch-build/issues/953 was reset and completed

Notification that testing was restarted
- [x] OpenSearch
- [x] OpenSearch-Dashboards
- [x] common-utils
- [x] alerting
- [x] anomaly-detection
- [x] asynchronous-search
- [x] dashboards-reports
- [x] dashboards-visualizations
- [x] index-management
- [x] job-scheduler
- [x] k-NN
- [x] performance-analyzer
- [x] security-dashboards-plugin
- [x] security
- [x] sql
- [x] trace-analytics
- [x] alerting-dashboards-plugin
- [x] index-management-dashboards-plugin
- [x] anomaly-detection-dashboards-plugin
- [x] cross-cluster-replication

Testing was completed
- [x] OpenSearch
- [x] OpenSearch-Dashboards
- [x] common-utils
- [x] alerting
- [x] anomaly-detection
- [x] asynchronous-search
- [x] dashboards-reports
- [x] dashboards-visualizations
- [x] index-management
- [x] job-scheduler
- [x] k-NN
- [x] performance-analyzer
- [x] security-dashboards-plugin
- [x] security
- [x] sql
- [x] trace-analytics
- [x] alerting-dashboards-plugin
- [x] index-management-dashboards-plugin
- [x] anomaly-detection-dashboards-plugin
- [x] cross-cluster-replication
